/** One catalogue shared by Workflow and authenticated agents. No run is started here. */
export const sourcingCatalog = {
  version: 1,
  checkedAt: "2026-09-16",
  recommendation: "Search the existing Compass ledger first. Use a bounded Maps run only when existing company coverage is insufficient, then qualify against published evidence.",
  methods: [
    { id: "ledger", name: "Compass company ledger", status: "Agent API available", when: "Reuse companies already researched or imported.", why: "Avoid buying the same records again and retain their evidence.", cost: "No discovery provider charge; agent usage still applies.", performance: "Existing records only. Evidence freshness and current coverage must be checked.", features: ["Search and filters", "Source evidence", "Existing contact identity"], url: "/leads", agent: "Use leads.search with bounded filters; preserve stable IDs and source evidence." },
    { id: "vortex", name: "Apify · Vortex Google Maps", status: "External agent run", when: "Find additional local companies by trade and area.", why: "Maps discovery can extend geographic coverage before website qualification.", cost: "Per-result billing; verify the actor's current price and account plan before setting a run cap.", performance: "No comparative benchmark asserted. Search coverage is incomplete and duplicate branches require reconciliation.", features: ["Business listings", "Location searches", "Dataset output"], url: "https://apify.com/vortex_data/google-maps", agent: "Inspect vortex_data/google-maps input schema and current price. Propose search terms, areas, result limit and explicit total spend cap before running. Retain run and dataset receipts." },
    { id: "outscraper", name: "Outscraper · Google Maps", status: "External agent run", when: "Compare an alternative Maps provider on the same small cohort.", why: "A controlled comparison can reveal coverage gaps without replacing the existing inventory.", cost: "Usage tiers and optional enrichment charges; check the current pricing page.", performance: "Local comparative yield and runtime are unmeasured. Compare qualified unique companies, not raw row counts.", features: ["Maps records", "Export", "Optional paid enrichment"], url: "https://outscraper.com/pricing/", agent: "Confirm connector/account access, current price and a bounded cohort. Keep optional enrichment off unless requested. Reconcile domains and branches before importing." },
    { id: "website", name: "Published website research", status: "External agent research", when: "Fill evidence gaps for known companies.", why: "First-party pages support installation fit and published contact claims.", cost: "Direct requests have no separate research provider fee; extraction/model costs depend on the selected tools.", performance: "Site availability varies. Cache pages, retain failed fetches and leave unsupported claims unknown.", features: ["First-party evidence", "Published contacts", "Cached excerpts"], url: "/sales/outbound?desk=evidence", agent: "Start with cached pages and direct HTTP extraction. Use a paid extraction fallback only where needed and within an agreed budget. Never guess emails or fit." },
  ],
  execution: { mode: "agent_handoff", startsPaidRuns: false, discoveryTool: "outbound.sourcing", endpoint: "/api/agent/outbound/sourcing", next: "Choose a method, define the geography and company criteria, inspect current costs and tool access, then ask the agent to prepare a bounded run. Store researched records through the Compass lead API." },
};
