import 'server-only'
import {createHash} from 'node:crypto'
import {z} from 'zod'
import type {SupabaseClient} from '@supabase/supabase-js'
import {canonicalPipeline,PipelineError} from './outbound-pipeline-schema'
import {pipelineDatabaseError,requirePipeline} from './outbound-pipeline-server'
import {renderPipelineTemplate,type TemplatePolicy} from './outbound-pipeline'
import {COMPANY_EXPORT_COLUMNS,RECIPIENT_EXPORT_COLUMNS,pipelineCsvRows,pipelineCsvCell,type PipelineJob,type PipelineJobItem} from './outbound-pipeline-jobs'
const id=z.string().min(1).max(160).regex(/^[a-zA-Z0-9_:.-]+$/)
const filters=z.record(z.enum(['q','city','suburb','country','fit','stage','status','draft_status','verification_status']),z.string().max(500))
const envelope=z.strictObject({schema_version:z.literal('outbound.pipeline.v1'),request_id:id.min(8),source:z.string().min(1).max(500),action:z.enum(['preview_apply','apply_chunk','create_export','export_chunk','preview_membership','membership_chunk']),job_id:id,expected_revision:z.number().int().nonnegative(),data:z.unknown()})
const membershipData=z.strictObject({list_id:id,operation:z.enum(['add','remove']),filters:z.record(z.enum(['list_id','q','city','suburb','country','fit','stage','status']),z.string().max(500)).optional(),company_ids:z.array(id).max(1000).optional()})
const applyData=z.strictObject({current_list_id:id,list_ids:z.array(id).min(1).max(100).optional(),template_version_id:id})
const exportData=z.strictObject({list_id:id,grain:z.enum(['companies','recipients']),columns:z.array(z.string()).min(1).max(30),filters:filters.optional(),company_ids:z.array(id).max(1000).optional()})
export async function readPipelineJob(db:SupabaseClient,id:string){requirePipeline();const result=await db.from('outbound_pipeline_jobs').select('*').eq('id',id).maybeSingle();pipelineDatabaseError(result.error);if(!result.data)throw new PipelineError('pipeline_not_found');return result.data as PipelineJob}
export async function pipelineJobItems(db:SupabaseClient,jobId:string,after?:string){requirePipeline();let q=db.from('outbound_pipeline_job_items').select('*').eq('job_id',jobId);if(after){try{const cursor=JSON.parse(Buffer.from(after,'base64url').toString());if(cursor.job_id!==jobId||typeof cursor.id!=='string')throw new Error();q=q.gt('id',cursor.id)}catch{throw new PipelineError('pipeline_cursor_scope_conflict')}}const result=await q.order('id').limit(101);pipelineDatabaseError(result.error);return {records:(result.data||[]).slice(0,100),next_after:(result.data||[]).length>100?Buffer.from(JSON.stringify({job_id:jobId,id:result.data![99].id})).toString('base64url'):null}}
export async function applyPipelineJob(db:SupabaseClient,input:unknown,actor:string){requirePipeline(true);let command:z.infer<typeof envelope>;try{command=envelope.parse(input);command.data=command.action==='preview_apply'?applyData.parse(command.data):command.action==='create_export'?exportData.parse(command.data):command.action==='preview_membership'?membershipData.parse(command.data):z.strictObject({}).parse(command.data)}catch(error){throw new PipelineError('pipeline_invalid_job_command: '+(error instanceof Error?error.message:'invalid'))}
 const hash=createHash('sha256').update(canonicalPipeline(command)).digest('hex');
 const previous=await db.from('outbound_pipeline_receipts').select('payload_hash,actor,receipt').eq('request_id',command.request_id).maybeSingle();pipelineDatabaseError(previous.error);if(previous.data){if(previous.data.payload_hash!==hash||previous.data.actor!==actor)throw new PipelineError('pipeline_idempotency_conflict');return previous.data.receipt}
 if(command.action==='create_export'){const data=command.data as z.infer<typeof exportData>;const allowed:readonly string[]=data.grain==='companies'?COMPANY_EXPORT_COLUMNS:RECIPIENT_EXPORT_COLUMNS;if(data.columns.some(c=>!allowed.includes(c))||new Set(data.columns).size!==data.columns.length)throw new PipelineError('pipeline_invalid_export_columns')}
 if(['preview_apply','create_export','preview_membership'].includes(command.action)){const result=await db.rpc('outbound_pipeline_job_create',{p_command:command,p_hash:hash,p_actor:actor});pipelineDatabaseError(result.error);return result.data}
 const job=await readPipelineJob(db,command.job_id);if(job.revision!==command.expected_revision)throw new PipelineError('pipeline_revision_conflict');
 const page=await db.from('outbound_pipeline_job_items').select('*').eq('job_id',job.id).eq('status','queued').order('id').limit(100);pipelineDatabaseError(page.error);const items=(page.data||[]) as PipelineJobItem[];if(!items.length)throw new PipelineError('pipeline_no_pending_job_items');let content='';let results:Record<string,unknown>[]=[];
 if(command.action==='apply_chunk'){if(job.kind!=='template_apply')throw new PipelineError('pipeline_job_kind_mismatch');const policy=job.config.policy as TemplatePolicy;results=items.map(item=>{const rendered=renderPipelineTemplate(policy,item.payload.signals||{});return rendered.missing.length?{item_id:item.id,status:'failed',reason:'Missing signals: '+rendered.missing.join(', ')}:{item_id:item.id,status:'applied',copy:rendered.copy}})}
 else if(command.action==='membership_chunk'){if(job.kind!=='membership')throw new PipelineError('pipeline_job_kind_mismatch');results=items.map(item=>({item_id:item.id,status:'applied'}))}
 else{if(job.kind!=='export')throw new PipelineError('pipeline_job_kind_mismatch');content=pipelineCsvRows(job.config.columns as string[],items.map(item=>item.payload.row||{}));results=items.map(item=>({item_id:item.id,status:'applied'}))}
 const result=await db.rpc('outbound_pipeline_job_commit',{p_command:command,p_hash:hash,p_actor:actor,p_results:results,p_content:content});pipelineDatabaseError(result.error);return result.data
}
export async function pipelineExportResponse(db:SupabaseClient,jobId:string,partAfter?:string){const job=await readPipelineJob(db,jobId);if(job.kind!=='export'||job.status!=='completed'||job.applied_count!==job.total_count)throw new PipelineError('pipeline_export_not_complete');if(partAfter!==undefined){let cursor=0;if(partAfter){try{const parsed=JSON.parse(Buffer.from(partAfter,'base64url').toString());if(parsed.job_id!==job.id||!Number.isSafeInteger(parsed.ordinal))throw new Error();cursor=parsed.ordinal}catch{throw new PipelineError('pipeline_cursor_scope_conflict')}}const parts=await db.from('outbound_pipeline_export_chunks').select('ordinal,content,row_count').eq('job_id',job.id).gt('ordinal',cursor).order('ordinal').limit(11);pipelineDatabaseError(parts.error);const rows=(parts.data||[]).slice(0,10);const next=(parts.data||[]).length>10?Buffer.from(JSON.stringify({job_id:job.id,ordinal:Number(rows.at(-1)!.ordinal)})).toString('base64url'):'';return new Response((job.config.columns as string[]).map(pipelineCsvCell).join(',')+'\r\n'+rows.map(row=>row.content).join(''),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="outbound-${job.id.replace(/[^a-zA-Z0-9_-]/g,'')}-after-${cursor}.csv"`,'Cache-Control':'private, no-store','X-Next-Cursor':next,'X-Export-Rows':String(rows.reduce((n,row)=>n+row.row_count,0))}})}let after=0;let header=true;let closed=false;const encoder=new TextEncoder();const stream=new ReadableStream<Uint8Array>({async pull(controller){try{if(header){header=false;controller.enqueue(encoder.encode((job.config.columns as string[]).map(pipelineCsvCell).join(',')+'\r\n'));return}const result=await db.from('outbound_pipeline_export_chunks').select('ordinal,content').eq('job_id',job.id).gt('ordinal',after).order('ordinal').limit(10);pipelineDatabaseError(result.error);if(closed)return;if(!result.data?.length){closed=true;controller.close();return}after=Number(result.data.at(-1)!.ordinal);controller.enqueue(encoder.encode(result.data.map(row=>row.content).join('')))}catch(error){if(!closed){closed=true;controller.error(error)}}},cancel(){closed=true}});return new Response(stream,{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="outbound-${job.id.replace(/[^a-zA-Z0-9_-]/g,'')}.csv"`,'Cache-Control':'private, no-store'}})}
