import test from 'node:test'
import assert from 'node:assert/strict'
import {loadTypescript} from './helpers/load-typescript.mjs'
const {assessFit,renderPipelineTemplate}=loadTypescript('src/lib/outbound-pipeline.ts')
const {parsePipelineCommand}=loadTypescript('src/lib/outbound-pipeline-schema.ts')
test('fit keeps missing evidence unknown and explicit exclusions separate',()=>{const c={id:'x',required:true,exclusion:false,evidence_ids:[],outcome:'unknown'};assert.equal(assessFit([c]),'unknown');assert.equal(assessFit([{...c,outcome:'failed'}]),'non_fit');assert.equal(assessFit([{...c,outcome:'supported'}]),'sure_fit');assert.equal(assessFit([{...c,exclusion:true,outcome:'supported'}]),'anti_icp')})
test('renderer uses saved fallback and exposes missing required slots',()=>{const p={mode:'deterministic',subject:'[[service]]',opener:'[[missing]]',body:'body',cta:'reply',unsubscribe:'opt out',slots:{service:{signal_ids:['service'],required:true,fallback:''}},followups:[]};const r=renderPipelineTemplate(p,{service:'Ducted'});assert.equal(r.copy.subject,'Ducted');assert.deepEqual(r.missing,['missing']);assert.throws(()=>renderPipelineTemplate({...p,mode:'ai'},{}),/executor_required/)})
test('command cannot set approval or run status through ordinary records',()=>{const c={schema_version:'outbound.pipeline.v1',request_id:'request-001',source:'fixture',operations:[{kind:'draft',expected_revision:0,record:{id:'x',approved:true}}]};assert.throws(()=>parsePipelineCommand(c),/invalid_operation/);assert.throws(()=>parsePipelineCommand({...c,operations:[{kind:'run',expected_revision:0,record:{id:'x',status:'completed'}}]}),/invalid_operation/)})

test('nested policy validation rejects null criteria and unknown authority fields',()=>{const c={schema_version:'outbound.pipeline.v1',request_id:'request-002',source:'fixture',operations:[{kind:'workflow',expected_revision:0,record:{id:'workflow',name:'Bad',policy:{criteria:null}}}]};assert.throws(()=>parsePipelineCommand(c),/invalid_record/);assert.throws(()=>parsePipelineCommand({schema_version:'outbound.pipeline.v1',request_id:'request-003',source:'fixture',action:'claim',run_id:'run',expected_revision:1,data:{approved:true}}),/invalid_run_data/)})
