const qs=new URLSearchParams(location.search),dir=qs.get('direction')||'relay',page=qs.get('screen')||'home',mode=qs.get('state')||'populated';document.body.classList.add(dir);document.title=`Compass · ${dir} · ${page}`;
const go=p=>`concept.html?direction=${dir}&screen=${p}`;
const cap=t=>`<div class="cap">${t}</div>`;
const tag=(t,p=false)=>`<span class="tag ${p?'pending':''}"><span class="dot"></span>${t}</span>`;
const btn=(t,a,primary=false)=>`<button class="btn ${primary?'primary':''}" data-action="${a}">${t}</button>`;
const link=(t,p,primary=false)=>`<a class="btn ${primary?'primary':''}" href="${go(p)}">${t}</a>`;
const ico=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">${({home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',inbox:'<path d="M4 4h16v16H4zM4 14h5l2 3h2l2-3h5"/>',outbound:'<path d="M4 6h14M13 1l5 5-5 5M4 13h7M4 20h14"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',tasks:'<path d="m3 6 2 2 3-4m-5 9 2 2 3-4m-5 9 2 2 3-4M11 6h10M11 13h10M11 20h10"/>',folder:'<path d="M3 5h7l3 3h8v12H3Z"/>',circle:'<circle cx="12" cy="12" r="8"/><path d="M12 7v10M7 12h10"/>'})[n]||'<rect x="4" y="4" width="16" height="16" rx="2"/>'}</svg>`;
const brand=`<div class="brand"><svg viewBox="0 0 28 28" fill="none" aria-hidden="true"><circle cx="14" cy="14" r="12" stroke="currentColor"/><path d="m9 19 3-9 8-3-3 9Z" fill="currentColor"/></svg>compass</div>`;
const destinations=[['Home','home','home'],['Inbox','inbox','inbox'],['Tasks','tasks','tasks'],['Calendar','calendar','calendar'],['Outbound','outbound','outbound'],['CRM','crm','circle'],['Clients','clients','folder'],['Installs','installs','folder'],['Planning','planning','folder'],['Settings','settings','circle']];
const known=p=>['home','inbox','outbound','editor'].includes(p);
function navLink(t,p,i){return `<a class="side-link ${(page===p||(page==='editor'&&p==='outbound'))?'active':''}" href="${known(p)?go(p):'#'}" ${known(p)?'':`data-action="scope:${p}"`}>${dir==='index'?`<span class="cap">${String(destinations.findIndex(x=>x[1]===p)+1).padStart(2,'0')}</span>`:ico(i)}${t}</a>`}
const side=`<aside class="side">${brand}<div class="side-group">${cap('Your day')}${destinations.slice(0,4).map(x=>navLink(...x)).join('')}</div><div class="side-group">${cap('Workspaces')}${destinations.slice(4,9).map(x=>navLink(...x)).join('')}</div><div class="side-foot">${navLink(...destinations[9])}<p class="small">Jules · Switchflow</p></div></aside>`;
const menu=`<button class="menu-button" data-action="menu" aria-label="Open workspace navigation">${ico('menu')}</button>`;
const top=dir==='relay'?`<header class="top">${brand}<nav class="main-nav" aria-label="Primary">${['home','inbox','outbound'].map(p=>`<a class="${page===p||(page==='editor'&&p==='outbound')?'active':''}" href="${go(p)}">${p==='home'?'Today':p[0].toUpperCase()+p.slice(1)}</a>`).join('')}<a href="#" data-action="scope:clients">Delivery</a><a href="#" data-action="scope:planning">Planning</a></nav><div class="flex"><span class="avatar account">JH</span>${menu}</div></header><div class="subbar"><span><b>Switchflow</b> &nbsp; / &nbsp; ${page==='editor'?'Outbound / Sydney Hvac':page[0].toUpperCase()+page.slice(1)}</span><span>Operator workspace &nbsp; · &nbsp; Sydney</span></div>`:`<header class="top"><div class="mobile-brand">${brand}</div><span class="location">SWITCHFLOW &nbsp; / &nbsp; ${page==='editor'?'OUTBOUND / SYDNEY HVAC':page.toUpperCase()}</span><span class="small top-date">Tuesday, 8 September</span><div class="flex"><span class="avatar account">JH</span>${menu}</div></header>`;
function heading(k,t,sub='',actions=''){return `<div class="page-head"><div>${cap(k)}<h1>${t}</h1>${sub?`<p>${sub}</p>`:''}</div><div class="flex">${actions}</div></div>`}
const brief=`Review existing installation candidates and finish one precise draft. Smart Handy is followed up; Roof Safety awaits an internal decision. Signing awaits payment connection.`;
const initial=`The service I’m offering handles follow-up on existing ducted-installation enquiries: collecting the job details, arranging suitable quote appointments and sending reminders.\n\nIt works around your existing estimating process.`;
const follow=`When a homeowner enquires about ducted aircon, is following up and getting a suitable quote appointment booked a headache, or is that already covered?\n\nIf useful, I can send a one-page outline of the follow-up process.`;
const cta=`Would a one-page outline of that process be useful, or is follow-up already covered?`;
const tasks=['Await Roof Safety’s internal decision','Client outcome reporting','Enquiry-to-booking delivery workflow','Onboarding and baseline capture'];
const context=`The conversation happened. Roof Safety asked for website and advertising ideas for two companies and will speak with his boss before making decisions.`;
function actionFacts(){return `<div class="record"><span class="small">Copy confirmation</span>${tag('Outstanding',true)}</div><div class="record"><span class="small">Opener review</span>${tag('Outstanding',true)}</div><div class="record"><span class="small">Instantly</span>${tag('Not linked')}</div>`}
function caseBody(){return `${cap('Agent task / 8 September')}${tag('Blocked',true)}<h2>Await Roof Safety’s<br>internal decision</h2><p class="case-copy">${context}</p><div class="note-box">${cap('Next action')}<h3>Wait for their internal decision.</h3><p>No unanswered call. No agreed follow-up date.</p></div><div class="flex">${btn('Open task ↗','task:0',true)}${btn('Snooze','snooze')}${btn('More ···','triage')}</div><div class="fields"><div>${cap('Work type')}<span>Sell</span></div><div>${cap('Source')}<span>Daily setup</span></div><div>${cap('Opportunity')}<span>Websites & advertising</span></div><div>${cap('Outcome')}<span>Uncertain</span></div></div>`}
const caseIndex=()=>tasks.map((t,i)=>`<button class="case-item ${i===0?'active':''}" data-action="${i===0?'open-case':'task:'+i}"><strong>${t}</strong><span class="small">${i===0?'Waiting · external decision':'Agent task · 8 September'}</span></button>`).join('');
function tabs(){return `<nav class="tabs" aria-label="Campaign sections"><a class="active" href="${go('editor')}">Sequence</a>${['Leads','Results','Experiment','Archive','Settings'].map(x=>`<button data-action="${x.toLowerCase()}">${x}</button>`).join('')}</nav>`}
function sources(){return `<div class="inbox-choices" aria-label="Inbox source"><button class="active" data-action="agents">Agents &nbsp; 4</button><button data-action="channel:Instantly">Instantly &nbsp; 50</button><button data-action="channel:Leads">Leads &nbsp; 33</button></div>`}
function email(n){return `<article class="email" data-step="${n}"><header class="email-header"><div class="row">${dir==='index'?`<span class="step-no">0${n}</span>`:''}<div><h3>${n===1?'Initial enquiry':'Follow-up'}</h3><span class="small">${n===1?'Send first':'Wait 3 days after email 1'}</span></div>${dir!=='index'?btn('Preview ↗','preview:'+n):''}</div></header><label><span class="subject-label">Subject${n===2?' / same thread':''}</span><input class="subject-input" aria-label="Email ${n} subject" value="${n===1?'ducted installation enquiries':''}" placeholder="${n===2?'Reply in the same thread':''}"></label>${n===1?`<div class="slot-label">Published factual opener</div><span class="token">{{personalization}}</span>`:''}<label><span class="slot-label">${n===1?'Service':'Diagnostic follow-up'}</span><textarea class="${n===2?'follow':''}" aria-label="Email ${n} body">${n===1?initial:follow}</textarea></label>${n===1?`<label><span class="slot-label">Permission CTA</span><textarea class="cta" aria-label="Email 1 CTA">${cta}</textarea></label>`:''}<p class="sign">Jules<br>Switchflow</p><p class="optout">Not relevant? Reply unsubscribe and I’ll leave it there.</p><details><summary class="small">Optional copy blocks</summary><div class="edit-controls">${btn('Risk reversal','insert:risk')}${btn('P.S.','insert:ps')}</div></details><div class="paper-foot row"><span class="small save-status">Saved snapshot · 8 Sep</span>${btn('Save draft','save')}</div></article>`}
function relayHome(){return heading('Tuesday / 08 September','Make the next handoff.','Your brief, the work it unlocks, and what is waiting.',btn('Capture a thought','capture'))+`<section class="launchpad"><div class="launch-label">${cap('Decision desk')}<strong>Today</strong>${cap('Brief / review')}</div><div class="launch-copy">${tag('Awaiting review',true)}<h2>Review installation candidates.<br>Finish one precise draft.</h2><p>Start with the Sydney companies already in Compass. Check fit and prior contact before preparing the next campaign.</p></div><div class="launch-action">${btn('Review the brief ↗','brief',true)}<p class="small">Preparation only.<br>Launch stays in Instantly.</p></div></section><div class="section-title"><h2>From decision to prepared campaign</h2><span class="cap">Sydney Hvac</span></div><section class="handoff">${[['01 / Start here','Review the brief','Choose the work for today.','Open brief','brief'],['02 / Research','Check the inventory','Relevance and previous contact.','View inventory','inventory'],['03 / Write','Finish the sequence','Copy and opener review pending.','Open sequence','editor'],['04 / Handoff','Prepare for Instantly','Review the draft and its cohort.','Preparation','preparation']].map((x,i)=>`<div class="stage ${i===0?'active':''}">${cap(x[0])}<h3>${x[1]}</h3><p>${x[2]}</p>${x[4]==='editor'?link(x[3]+' ↗','editor'):btn(x[3]+' ↗',x[4])}</div>`).join('')}</section><div class="lower"><section class="card">${cap('Waiting / Roof Safety')}<h3>Decision with their boss.</h3><p>Websites and advertising for two companies. No follow-up date agreed.</p>${link('Read the context ↗','inbox')}</section><section class="card">${cap('Preparation / Payment')}<h3>Signing awaits connection.</h3><p>Verified receiving instructions are still needed before signing can proceed.</p>${btn('View setup context ↗','payment')}</section><section class="card">${cap('Outbound / Snapshot')}<div class="metric-inline"><span><b>162</b>sent</span><span><b>1.3%</b>reply rate</span></div><p class="small">Instantly · 8 Sep, 18:27 AEST.<br>Review sending status before acting.</p></section></div>`}
function folioHome(){return heading('Your working desk','A little more clarity.','Tuesday, 8 September · Switchflow',btn('Capture','capture'))+`<div class="folio-home"><div><nav class="folder-tabs" aria-label="Work folder"><button class="active" data-action="brief">Today’s brief</button><a href="${go('outbound')}">Outbound</a><button data-action="payment">Delivery</button></nav><article class="document brief-note"><div class="document-head row">${cap('Daily setup / 08.09')}${tag('Review needed',true)}</div><h2>One precise draft.<br>Built on the right companies.</h2><p>Review the existing Sydney installation candidates. Confirm relevance and prior contact, then continue the saved Sydney Hvac sequence.</p><div class="flex">${btn('Review today’s brief ↗','brief',true)}${link('Continue the draft','editor')}</div><div class="work-index">${cap('Inside this brief')}<div class="record"><span class="cap">01</span><div><h3>Sydney installation candidates</h3><p>Research fit before assigning leads.</p></div>${btn('Open ↗','inventory')}</div><div class="record"><span class="cap">02</span><div><h3>Sydney Hvac</h3><p>Saved copy · review outstanding.</p></div>${link('Write ↗','editor')}</div><div class="record"><span class="cap">03</span><div><h3>Payment connection</h3><p>Receiving instructions needed.</p></div>${btn('View ↗','payment')}</div></div><div class="capture-strip"><div><h3>A thought to come back to?</h3><p class="small">Capture it without leaving the desk.</p></div>${btn('＋ Add note','capture')}</div></article></div><aside class="desk-notes"><section class="pinned">${cap('Waiting / Roof Safety')}<h3>The next move<br>is theirs.</h3><p>They will speak with their boss about websites and advertising. No follow-up date agreed.</p>${link('Read context ↗','inbox')}</section><section class="aside-note">${cap('In your inbox')}<div class="record"><span class="small">Agent items</span><strong>4</strong></div><div class="record"><span class="small">Instantly items</span><strong>50</strong></div><div class="record"><span class="small">Lead items</span><strong>33</strong></div><p>Retained queue items from the 8 September snapshot.</p>${link('Open inbox ↗','inbox')}</section></aside></div>`}
function indexHome(){return `<header class="register-heading"><div class="date-number">08</div><div>${cap('September / Tuesday')}<h1>The operating register.</h1><p>Decisions first. Preparation next. Waiting stays visible.</p></div>${btn('＋ Capture','capture')}</header><section class="register"><div class="register-row head"><span class="cap">TYPE</span><span class="cap">WORK / CONTEXT</span><span class="cap state-col">STATE</span><span class="cap">ACTION</span></div><div class="register-row next"><span class="label">NEXT<br>DECISION</span><div><h2>Review installation candidates.<br>Finish one precise draft.</h2><p>From today’s operator brief. Start with existing Sydney companies.</p></div><div class="state-col">${tag('Review needed')}</div><div class="row-action">${btn('Review brief ↗','brief')}</div></div>${[['01 / PREPARE','Sydney installation candidates','Check relevance and previous contact.','Inventory','inventory'],['02 / WRITE','Sydney Hvac','Draft sequence · copy and opener review outstanding.','Draft','editor'],['03 / RESOLVE','Payment connection','Signing awaits verified receiving instructions.','Pending','payment'],['WAITING','Roof Safety’s internal decision','Their boss is reviewing websites and advertising.','Blocked','inbox']].map(x=>`<div class="register-row"><span class="label">${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div><div class="state-col">${tag(x[3],x[3]==='Blocked')}</div><div class="row-action">${known(x[4])?link('Open ↗',x[4]):btn('Open ↗',x[4])}</div></div>`).join('')}</section><div class="register-bottom"><section><div class="row"><h3>Outbound / snapshot</h3>${cap('18:27 AEST')}</div><div class="receipt"><div><span>SENT TODAY</span><strong>162</strong></div><div><span>REPLY RATE</span><strong>1.3%</strong></div></div><p class="small">Instantly · 8 September. Sending status needs review.</p></section><section><div class="row"><h3>Inbox / retained items</h3>${link('Open queue ↗','inbox')}</div><div class="receipt"><div><span>AGENTS</span><strong>4</strong></div><div><span>INSTANTLY</span><strong>50</strong></div><div><span>LEADS</span><strong>33</strong></div></div></section></div>`}
function relayInbox(){return heading('Communications / Cases','Keep the next action in view.','Agents · retained work from the 8 September snapshot')+sources()+`<div class="case-layout"><nav class="case-index" aria-label="Agent cases">${caseIndex()}</nav><article class="case-file"><button class="back" data-action="back-case">← Back to cases</button>${caseBody()}</article><aside class="action-spine">${cap('Handoff status')}${tag('Waiting',true)}<h3>Internal decision pending.</h3><p>The conversation is complete. The opportunity is still uncertain.</p><p>No new follow-up date was agreed.</p>${btn('Open linked task','task:0',true)}${btn('View source note','task:0')}</aside></div>`}
function folioInbox(){return heading('Correspondence','Inbox, with context.','A case stays together, from source to decision.')+sources()+`<div class="inbox-folder"><nav class="letter-index" aria-label="Agent cases">${caseIndex()}</nav><div class="case-file"><nav class="folder-tabs"><button class="active" data-action="task:0">Roof Safety</button><button data-action="task:0">Source note</button></nav><article class="document"><button class="back" data-action="back-case">← Back to correspondence</button>${caseBody()}</article></div></div>`}
function indexInbox(){return heading('Communications / Register','Inbox','Expand a case in place. Keep the surrounding queue visible.')+sources()+`<div class="register"><div class="queue-head"><span>ID</span><span>ITEM</span><span class="queue-source">SOURCE</span><span class="queue-state">STATE</span><span></span></div>${tasks.map((t,i)=>`<button class="queue-button" data-action="expand:${i}" aria-expanded="${i===0}" aria-controls="case-${i}"><span class="cap">0${i+1}</span><strong>${t}</strong><span class="small queue-source">Daily setup</span><span class="queue-state">${tag(i===0?'Blocked':'Agent task',i===0)}</span><span class="arrow">${i===0?'−':'＋'}</span></button><div class="inline-case" id="case-${i}" ${i===0?'':'hidden'}><section><h2>${i===0?'Internal decision pending.':t}</h2><p>${i===0?context:'The title is from the live Agents queue. Open the source record to review its full context; no additional facts were added to this concept.'}</p></section><section>${cap(i===0?'Next action':'Source record')}<p>${i===0?'Wait for their decision. No follow-up date was agreed.':'Review the task before deciding what to do next.'}</p><div class="flex" style="margin-top:18px">${btn('Open task ↗','task:'+i,true)}${i===0?btn('Snooze','snooze'):''}</div></section></div>`).join('')}</div><p class="register-caption">Agents: 4 items · retained queue, not new replies</p>`}
function relayEditor(){return heading('Outbound / Sydney Hvac','Write it. Then review it.','Draft · Installation booking',btn('Preparation','preparation',true))+tabs()+`<nav class="sequence-rail" aria-label="Sequence steps"><button class="step-switch active" data-action="step:1"><span class="cap">01</span><div><strong>Initial enquiry</strong><span class="small">Send first</span></div></button><span class="cap">→ Wait 3 days →</span><button class="step-switch" data-action="step:2"><span class="cap">02</span><div><strong>Follow-up</strong><span class="small">Same thread</span></div></button></nav><div class="editor-grid"><div><div id="email-1">${email(1)}</div><div id="email-2" hidden>${email(2)}</div></div><aside class="editor-context">${cap('Sydney Hvac / preparation')}<h2 style="margin:14px 0">One campaign.<br>Clear handoff.</h2><p class="small">HVAC · Sydney<br>Installation booking</p>${actionFacts()}${btn('Review preparation ↗','preparation',true)}</aside></div><div class="tool-shelf"><div>${cap('Writing shelf')}<h3>Bring in a component when you need it.</h3></div><div class="flex">${btn('Library','library')}${btn('QA & variables','qa')}${btn('Copy history','archive')}</div></div>`}
function folioEditor(){return heading('Outbound / Draft workspace','Sydney Hvac','Installation booking · Saved Compass sequence',btn('Preparation','preparation',true))+tabs()+`<div class="editor-desk"><nav class="folder-tabs" aria-label="Sequence steps"><button class="active step-switch" data-action="step:1">01 &nbsp; Initial enquiry</button><button class="step-switch" data-action="step:2">02 &nbsp; Follow-up</button></nav><div class="document"><div class="manuscript"><div><div id="email-1">${email(1)}</div><div id="email-2" hidden>${email(2)}</div></div><aside class="margin-notes">${cap('Margin notes')}<h3>Write for a reply.</h3><p>The opener stays factual. The ask stays small. Read the whole email before reviewing.</p>${btn('Writing library','library')}${btn('Variables & QA','qa')}<div class="note-box" style="padding:14px;margin-top:25px"><span class="small">Follow-up after<br><b>3 days</b></span></div></aside></div></div><div class="paper-tools"><span class="small">Draft · Copy and opener review outstanding</span><div class="edit-controls">${btn('Library','library')}${btn('Preparation','preparation')}${btn('Preview','preview:active')}</div></div></div>`}
function indexEditor(){return heading('Outbound / Sequence register','Sydney Hvac','Read the whole sequence together. Preserve the exact saved copy.',btn('Review preparation','preparation',true))+tabs()+`<div class="check-strip"><span>OFFER / installation-booking</span><span>MARKET / hvac · sydney</span><span>INSTANTLY / not linked</span></div><div class="sequence-register">${email(1)}${email(2)}</div><div class="sequence-footer"><p class="small">Copy unconfirmed · Opener review outstanding · 3-day follow-up</p><div class="edit-controls">${btn('Library','library')}${btn('Preview both','preview:both')}${btn('Variables & QA','qa')}</div></div>`}
const campaigns=[['Sydney Hvac','Sydney','Draft · Installation booking','editor'],['Melbourne Plumber','Melbourne','Linked to Instantly','campaign:1'],['HVAC | AU | 50 | capture 24 aug','AU','Linked to Instantly','campaign:2']];
function table(){return `<div class="table-scroll"><table class="data-table"><thead><tr><th>CAMPAIGN</th><th>MARKET</th><th>CONTEXT</th><th></th></tr></thead><tbody>${campaigns.map(x=>`<tr><td><strong>${x[0]}</strong><small>${x[2]}</small></td><td>${x[1]}</td><td>${x[2]}</td><td>${known(x[3])?link('Open ↗',x[3]):btn('Inspect',x[3])}</td></tr>`).join('')}</tbody></table></div>`}
function outboundHead(){return heading('Growth / Campaign work','Outbound','Preparation and platform state stay distinct.',btn('New campaign','new',true))+`<nav class="tabs" aria-label="Outbound views"><button class="active" data-action="campaigns">Campaigns</button><button data-action="scope:calendar">Calendar</button><button data-action="timeline">Timeline</button><button data-action="library">Craft library</button><button data-action="offers">Offers & tests</button></nav>`}
function relayOutbound(){return outboundHead()+`<div class="outbound-board"><article class="campaign-focus"><div class="row">${cap('Continue preparing')}${tag('Draft')}</div><h2>Sydney Hvac</h2><p>Installation booking · Sydney residential ducted installation enquiries.</p><div class="mini-stages">${tag('Copy review pending',true)}${tag('Opener review pending',true)}${tag('Instantly not linked')}</div><div class="flex">${link('Continue sequence ↗','editor',true)}${btn('Preparation','preparation')}</div></article><section class="card">${cap('Next campaigns')}<div class="record"><div><h3>Melbourne Plumber</h3><p>Plumber · Melbourne · Instantly linked</p></div>${btn('Open','campaign:1')}</div><div class="record"><div><h3>HVAC | AU | 50 | capture 24 aug</h3><p>HVAC · AU · Instantly linked</p></div>${btn('Open','campaign:2')}</div></section></div><div class="section-title"><h2>Recommended, before the next handoff</h2></div><section class="card row"><div>${cap('Agent recommendation')}<h3>Sydney Locksmith | 65 | Sep</h3><p>Review current campaign context before moving it to next.</p></div>${btn('Review recommendation','recommended')}</section>`}
function folioOutbound(){return outboundHead()+`<div class="campaign-shelf"><section><nav class="folder-tabs"><a class="active" href="${go('editor')}">Working draft</a></nav><article class="document">${cap('Sydney / HVAC')}<h2>Sydney Hvac</h2><p>Installation booking</p><div class="shelf-facts"><div class="row"><span>Copy</span>${tag('Unconfirmed',true)}</div><div class="row"><span>Openers</span>${tag('Review pending',true)}</div><div class="row"><span>Instantly</span>${tag('Not linked')}</div></div>${link('Open the sequence ↗','editor',true)}</article></section><section><nav class="folder-tabs"><button class="active" data-action="campaigns">Next campaigns</button></nav><article class="document"><div class="record"><div><h3>Melbourne Plumber</h3><p>Plumber · Melbourne</p></div>${btn('Open','campaign:1')}</div><div class="record"><div><h3>HVAC | AU | 50 | capture 24 aug</h3><p>HVAC · AU</p></div>${btn('Open','campaign:2')}</div><p class="small">Both records are linked to Instantly. Open the source to review their sending state.</p></article></section></div><div class="quiet-row"><div>${cap('Recommended')}<h3>Sydney Locksmith | 65 | Sep</h3><p class="small">Review before moving to next.</p></div>${btn('Read recommendation','recommended')}</div>`}
function indexOutbound(){return outboundHead()+`<section class="outbound-lead"><strong>→</strong><div>${cap('Next preparation')}<h2>Finish the Sydney Hvac draft.</h2><p>Copy and opener review are outstanding. The campaign has no Instantly link.</p></div><div class="flex">${link('Open sequence ↗','editor',true)}</div></section>${table()}<div class="footer-line"><span>Compass preparation records · 8 September snapshot</span>${btn('Review recommendation','recommended')}</div>`}
const renders={relay:{home:relayHome,inbox:relayInbox,editor:relayEditor,outbound:relayOutbound},folio:{home:folioHome,inbox:folioInbox,editor:folioEditor,outbound:folioOutbound},index:{home:indexHome,inbox:indexInbox,editor:indexEditor,outbound:indexOutbound}};
function dataState(){return heading('Workspace / '+page,'A clear place to resume.')+`<section class="state-box" ${mode==='error'?'role="alert"':mode==='loading'?'aria-busy="true"':''}>${cap(mode==='loading'?'Loading this view':mode==='empty'?'No matching records':'Refresh interrupted')}<h2>${mode==='loading'?'Bringing the work into view.':mode==='empty'?'Nothing matches this view.':'This view could not refresh.'}</h2>${mode==='loading'?'<div class="skeleton"></div><div class="skeleton short"></div>':`<p>${mode==='empty'?'Clear the current view and return to the available work.':'Your draft remains in place. Retry when the connection is available.'}</p>${link(mode==='empty'?'Return to work':'Retry this view',page,true)}`}</section>`}
const mobile=`<nav class="mobile-nav" aria-label="Mobile primary">${[['Home','home','home'],['Inbox','inbox','inbox'],['Outbound','outbound','outbound']].map(([t,p,i])=>`<a class="${page===p||(page==='editor'&&p==='outbound')?'active':''}" href="${go(p)}">${ico(i)}${t}</a>`).join('')}<button data-action="menu">${ico('menu')}More</button></nav>`;
document.querySelector('#app').innerHTML=`<div class="shell">${dir==='relay'?'':side}<div class="workspace">${top}<main class="main" id="main">${mode==='populated'?renders[dir][page]():dataState()}<footer class="stamp">${dir.toUpperCase()} · ROUND 2 DESIGN STUDY · 8 SEP SNAPSHOT · LOCAL PROTOTYPE, NO LIVE WRITES</footer></main></div></div>${mobile}`;
const dialog=document.querySelector('#dialog'),db=document.querySelector('#dialog-body');let returnTo,activeStep=1;
function show(title,body){returnTo=document.activeElement;db.innerHTML=`${cap('Compass / '+dir)}<h2 id="dialog-title">${title}</h2>${body}`;if(!dialog.open)dialog.showModal()}
function toast(t){const el=document.querySelector('.toast');el.textContent=t;el.hidden=false;setTimeout(()=>el.hidden=true,4500)}
document.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>returnTo?.isConnected&&returnTo.focus());
function previewText(n){const em=document.querySelector(`[data-step="${n}"]`);return (n===1?'{{personalization}}\n\n':'')+em.querySelector(`[aria-label="Email ${n} body"]`).value+(n===1?'\n\n'+em.querySelector('.cta').value:'')+'\n\nJules\nSwitchflow\n\nNot relevant? Reply unsubscribe and I’ll leave it there.'}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;e.preventDefault();const a=el.dataset.action;
if(a==='menu'){show('Your workspace',`<div class="menu-grid">${destinations.map(([t,p])=>`<a href="${known(p)?go(p):'#'}" ${known(p)?'':`data-action="scope:${p}"`}>${t}${known(p)?'':'<br><small>Planned in full rollout</small>'}</a>`).join('')}</div><p class="small">Core concepts are navigable. Other destinations retain their capabilities in the production plan.</p>`);return}
if(a==='brief'){show('Today’s brief',`<p>${brief}</p><div class="note-box"><h3>Prepare and validate.</h3><p>Review the existing Sydney companies for relevance and previous contact. Qualified cohort assignment and final review remain outstanding.</p></div><p class="small">Recorded 8 September. The campaign stays a draft.</p><div class="flex">${btn('Accept brief','accept',true)}${btn('Dismiss brief','dismiss')}</div>`);return}
if(a==='accept'||a==='dismiss'){dialog.close();toast(`Prototype: brief ${a==='accept'?'accepted':'dismissed'}. No live record changed.`);return}
if(a==='capture'){show('Capture a thought',`<p>Leave the loose thought here. Review it before turning it into work.</p><textarea class="capture-input" aria-label="Thought" placeholder="What needs your attention?"></textarea>${btn('Keep this note','keep-note',true)}`);return}
if(a==='keep-note'){const value=db.querySelector('textarea').value.trim();if(!value){db.querySelector('textarea').focus();return}show('Note captured for review',`<p id="note-copy" style="white-space:pre-wrap"></p><p class="small">Local prototype only. Production uses the existing brain-dump review and task-selection flow.</p>`);db.querySelector('#note-copy').textContent=value;return}
if(a==='open-case'){document.querySelector('.case-layout,.inbox-folder').classList.add('detail');document.querySelector('.back').focus();return}
if(a==='back-case'){document.querySelector('.case-layout,.inbox-folder').classList.remove('detail');document.querySelector('[data-action="open-case"]').focus();return}
if(a.startsWith('expand:')){const n=a.split(':')[1],open=el.getAttribute('aria-expanded')==='true';el.setAttribute('aria-expanded',String(!open));el.querySelector('.arrow').textContent=open?'＋':'−';document.querySelector('#case-'+n).hidden=open;return}
if(a.startsWith('step:')){activeStep=Number(a.split(':')[1]);for(let n of [1,2]){document.querySelector('#email-'+n).hidden=n!==activeStep}document.querySelectorAll('.step-switch').forEach(x=>x.classList.toggle('active',x.dataset.action===a));return}
if(a.startsWith('preview:')){const value=a.split(':')[1],nums=value==='both'?[1,2]:[value==='active'?activeStep:Number(value)];show(nums.length===2?'The complete sequence':'Email preview',nums.map(n=>`<section><h3>Email ${n}${n===2?' · after 3 days':''}</h3><p id="preview-${n}" style="white-space:pre-wrap;line-height:1.9"></p></section>`).join('')+'<p class="small">Select a real verified lead in production to resolve merge values.</p>');nums.forEach(n=>db.querySelector('#preview-'+n).textContent=previewText(n));return}
if(a==='save'){document.querySelectorAll('.save-status').forEach(x=>x.textContent='Prototype save acknowledged');toast('Prototype: draft saved in this view. Live Compass is unchanged.');return}
if(a==='snooze'){show('Snooze this item',`<p>Keep the waiting case out of immediate review until tomorrow.</p>${btn('Snooze for 24 hours','snooze-confirm',true)}<p class="small">This demonstrates local feedback only.</p>`);return}
if(a==='snooze-confirm'){dialog.close();toast('Prototype: snoozed for 24 hours. No live task changed.');return}
if(a==='library'){show('Writing library',`<p>Compare source structures before applying one to the draft.</p><input class="search" aria-label="Search structures" placeholder="Search structures…"><div id="library-results">${['Nick 4-step','Nick 3-step','Platten AIDA','Connor 3-paragraph'].map((t,i)=>`<div class="record" data-name="${t.toLowerCase()}"><div><h3>${t}</h3><p class="small">Source structure${i===3?' · current campaign':''}</p></div>${btn('Inspect','structure:'+i)}</div>`).join('')}</div>`);return}
if(a.startsWith('structure:')){const n=Number(a.split(':')[1]),names=['Nick 4-step','Nick 3-step','Platten AIDA','Connor 3-paragraph'];show(names[n],`<p>Source structure from the existing Compass library. Keep source provenance distinct from Jules’ own copy.</p><p class="small">The current campaign uses Connor 3-paragraph. This design study preserves its saved sequence.</p>`);return}
if(a.startsWith('insert:')){const em=dir==='index'?document.querySelector('[data-step="1"]'):document.querySelector(`[data-step="${activeStep}"]`),label=a.endsWith('ps')?'P.S.':'Risk reversal';const block=document.createElement('label');block.innerHTML=`<span class="slot-label">${label}</span><textarea aria-label="${label}" placeholder="Add only supported copy"></textarea>`;em.querySelector('.sign').before(block);block.querySelector('textarea').focus();toast('Optional block added to the local draft.');return}
if(a.startsWith('task:')){const i=Number(a.split(':')[1]);show(tasks[i],`<p>${i===0?context:'Verified title from the retained Agents queue. Its full task body was not copied into this design study.'}</p>${i===0?'<div class="note-box"><h3>Waiting on an internal decision.</h3><p>No follow-up date agreed. Commercial outcome remains uncertain.</p></div>':''}<p class="small">Source: daily setup · 8 September snapshot.</p>`);return}
const descriptions={preparation:['Campaign preparation',`<p>Sydney Hvac · installation-booking · HVAC / Sydney.</p>${actionFacts()}<p>Qualified cohort assignment, prior-contact reconciliation and final rendered-copy review remain outstanding. Launch stays in Instantly.</p>`],inventory:['Review existing inventory','<p>Start with existing Greater Sydney residential ducted installation/replacement companies and a published homeowner quote journey.</p><p>Check source evidence and prior contact before assigning a qualified cohort. Research fit is not sales qualification.</p>'],payment:['Payment connection','<p>Signing awaits a payment connection and verified receiving instructions. No payment status or account detail is invented for the design study.</p>'],qa:['Variables and copy review','<p>Keep the published opener, signature and opt-out intact. Preview both steps using a verified lead before launch.</p><p>The saved follow-up delay is 3 days. Copy confirmation and opener review are outstanding.</p>'],archive:['Saved copy history','<p>Current source: Sydney Hvac, updated 8 September at 19:32 AEST.</p><p>Production retains saved revisions, comparison and explicit restoration. This prototype has not added or replaced a saved revision.</p>'],results:['Results when the data arrives','<p>No Instantly link exists for this draft. Performance remains unavailable until there is real delivery data.</p>'],experiment:['Exploratory campaign','<p>Saved experiment: solo, queued, factor none.</p><p>Review qualified conversations and explicit objections before changing geography or promise. No controlled winner is claimed.</p>'],leads:['Campaign leads','<p>The brief says qualified cohort assignment remains outstanding. Production retains the actual lead list, filters and rendered preview; this concept adds no fictitious recipients.</p>'],settings:['Campaign settings','<p>Installation booking · Sydney · HVAC · draft.</p><p>Instantly is not linked. Review the preparation panel before any handoff.</p>'],recommended:['Sydney Locksmith | 65 | Sep','<p>Existing agent recommendation. Review the current campaign context before moving it to next.</p>'],offers:['Offers and tests','<p>Retain offer contracts, economics, test cells and campaign copy. This is a new interface for the same business capabilities.</p>'],timeline:['Campaign timeline','<p>Retain the existing go-live dates and timeline view. Do not invent time blocks or personal appointments.</p>'],new:['Start a campaign draft','<p>Production retains name, offer, market, sequence and an explicitly saved draft. This study does not create a campaign.</p>'],campaigns:['Next campaigns',`<p>Sydney Hvac, Melbourne Plumber, and HVAC | AU | 50 | capture 24 aug are the recorded next campaigns in this snapshot.</p>`],triage:['Triage actions',`<div class="flex">${btn('Snooze','snooze')}${btn('Open task','task:0')}</div><p>Production retains read/done, undo, lifecycle and source-specific actions.</p>`]};
if(a.startsWith('channel:')){show(a.split(':')[1]+' queue','<p>The drawn case uses the Agents source. Production preserves this source’s own queue, classification and links; counts are retained items, not necessarily new unread replies.</p>');return}
if(a.startsWith('scope:')){show('Full product navigation',`<p>This exploration draws Home, Inbox, Outbound and the sequence editor. The full rollout retains:</p><ul class="scope-index"><li>Tasks and execution evidence</li><li>Campaign calendar and timeline</li><li>CRM and lead evidence</li><li>Clients and communication</li><li>Installs and dependencies</li><li>Planning, projects and functions</li><li>Offers, economics and tests</li><li>Finances and retention</li><li>Settings and integrations</li></ul><p class="small">Direction and responsive reference approval precede full product implementation.</p>`);return}
if(a.startsWith('campaign:')){show(campaigns[Number(a.split(':')[1])][0],'<p>This existing record is linked to Instantly. Its sending status must be checked in the source before action. Sydney Hvac is the fully drawn editor in this study.</p>');return}
if(descriptions[a])show(...descriptions[a]);
});
document.addEventListener('input',e=>{if(e.target.closest('.email'))e.target.closest('.email').querySelector('.save-status').textContent='Unsaved local changes';if(e.target.matches('[aria-label="Search structures"]'))db.querySelectorAll('[data-name]').forEach(x=>x.hidden=!x.dataset.name.includes(e.target.value.toLowerCase()))});
