'use client';
import { useRef, useState } from 'react';
import { Plus, Copy as CopyIcon, ArrowUp, ArrowDown, SlidersHorizontal } from 'lucide-react';
import { COPY_LABELS, newCopyVariant, type CopyComponent, type CopyControlConfig, type CopyVariant } from '@/lib/copy-control';
import type { SignalDefinition } from '@/lib/outbound-pipeline';
import { Field } from './PipelineForms';
export function CopyControlStudio({ value, signals, onChange, onPreviewVariant }: { value: CopyControlConfig; signals: SignalDefinition[]; onChange: (value: CopyControlConfig) => void; onPreviewVariant?: (component: string, variant: string) => void }) {
  const [componentId, setComponentId] = useState('opener'), [variantId, setVariantId] = useState(''), [slotName, setSlotName] = useState('');
  const textRef = useRef<HTMLTextAreaElement>(null);
  const component = value.components.find(c => c.id === componentId) || value.components[0];
  const variant = component.variants.find(v => v.id === variantId) || component.variants[0];
  const updateComponent = (patch: Partial<CopyComponent>) => onChange({ ...value, components: value.components.map(c => c.id === component.id ? { ...c, ...patch } : c) });
  const updateVariant = (patch: Partial<CopyVariant>) => updateComponent({ variants: component.variants.map(v => v.id === variant.id ? { ...v, ...patch } : v) });
  function addVariant(duplicate = false) {
    const id = crypto.randomUUID();
    const next = duplicate ? { ...structuredClone(variant), id, name: `${variant.name} copy` } : newCopyVariant(id);
    updateComponent({ variants: [...component.variants, next] }); setVariantId(id);
  }
  function moveVariant(delta: number) {
    const variants = [...component.variants], i = variants.findIndex(v => v.id === variant.id), j = i + delta;
    if (j < 0 || j >= variants.length) return;
    [variants[i], variants[j]] = [variants[j], variants[i]]; updateComponent({ variants });
  }
  function insertToken(token: string) {
    const input = textRef.current, start = input?.selectionStart ?? variant.text.length, end = input?.selectionEnd ?? start;
    updateVariant({ text: variant.text.slice(0, start) + token + variant.text.slice(end) });
    requestAnimationFrame(() => { input?.focus(); input?.setSelectionRange(start + token.length, start + token.length); });
  }
  const experiment = value.experiment;
  return <section className="cc-studio" aria-label="Copy Control editor">
    <nav className="cc-parts" aria-label="Email elements">
      {value.components.map(c => <button type="button" key={c.id} aria-pressed={component.id === c.id} onClick={() => { setComponentId(c.id); setVariantId(''); setSlotName(''); }}>{c.kind === 'custom' ? c.name : COPY_LABELS[c.kind]}{!c.enabled && <small> off</small>}</button>)}
      <button type="button" aria-label="Add custom email element" onClick={() => { const id = crypto.randomUUID(); onChange({ ...value, components: [...value.components, { id, kind: 'custom', name: 'PS', enabled: true, position: 'after_cta', selection: 'priority', pinned_variant_id: null, variants: [newCopyVariant(crypto.randomUUID(), 'Default', 'PS: ')] }] }); setComponentId(id); setVariantId(''); }}><Plus size={15} />Extra</button>
    </nav>
    <div className="cc-layout">
      <aside className="cc-variants" aria-label={`${component.name} variants`}>
        <div className="cc-rail-label">{component.name}<span>{component.variants.length}</span></div>
        {component.variants.map((v, i) => <button type="button" className="cc-variant" aria-pressed={variant.id === v.id} key={v.id} onClick={() => setVariantId(v.id)}><span>{v.name || 'Unnamed variant'}</span><small>{i + 1} · {v.mode === 'ai' ? 'AI' : 'Template'}{!v.enabled ? ' · off' : ''}{component.pinned_variant_id === v.id ? ' · pinned' : ''}</small></button>)}
        <button type="button" className="cc-add" onClick={() => addVariant()}><Plus size={14} />New variant</button>
        <details className="cc-routing"><summary>Matching order</summary><Field label="Choose an eligible variant"><select value={component.selection} onChange={e => updateComponent({ selection: e.target.value as 'priority' | 'auto' })}><option value="priority">First eligible, in list order</option><option value="auto">Auto-pick by signal coverage</option></select></Field><p>Auto-pick prefers more supported signals, then stronger evidence. It is not a prediction of reply rate.</p><Field label="Pin a variant"><select value={component.pinned_variant_id || ''} onChange={e => updateComponent({ pinned_variant_id: e.target.value || null })}><option value="">No pin</option>{component.variants.filter(v => v.enabled).map(v => <option value={v.id} key={v.id}>{v.name}</option>)}</select></Field><p>A pinned variant holds when its inputs are unavailable. It does not invent a fallback.</p></details>
      </aside>
      <div className="cc-page" key={component.id + variant.id}>
        <div className="cc-page-head"><input className="cc-title" aria-label="Variant name" value={variant.name} placeholder="Name this variant" onChange={e => updateVariant({ name: e.target.value })} /><div className="cc-tools"><button type="button" aria-label="Duplicate variant" title="Duplicate" onClick={() => addVariant(true)}><CopyIcon size={15} /></button><button type="button" aria-label="Move variant up" title="Move up" disabled={component.variants[0].id === variant.id} onClick={() => moveVariant(-1)}><ArrowUp size={15} /></button><button type="button" aria-label="Move variant down" title="Move down" disabled={component.variants.at(-1)?.id === variant.id} onClick={() => moveVariant(1)}><ArrowDown size={15} /></button></div></div>
        <div className="cc-mode"><div className="op-segmented" aria-label="Generation mode"><button type="button" aria-pressed={variant.mode === 'template'} onClick={() => updateVariant({ mode: 'template' })}>My template</button><button type="button" aria-pressed={variant.mode === 'ai'} onClick={() => updateVariant({ mode: 'ai' })}>AI writing</button></div><button type="button" onClick={() => onPreviewVariant?.(component.id, variant.id)}>Preview this variant</button><label className="op-check"><input type="checkbox" checked={variant.enabled} onChange={e => updateVariant({ enabled: e.target.checked })} />Enabled</label></div>
        <label className="cc-editor-label" htmlFor={`copy-text-${variant.id}`}>{variant.mode === 'ai' ? 'Optional scaffold · AI may rewrite this element' : component.name}</label>
        <textarea ref={textRef} id={`copy-text-${variant.id}`} className="cc-writing" rows={component.kind === 'subject' ? 3 : component.kind === 'body' ? 7 : 4} spellCheck value={variant.text} onChange={e => updateVariant({ text: e.target.value })} placeholder={component.kind === 'subject' ? '[[location]] + [[service]]' : 'Write it your way. Insert researched facts using [[variables]].'} />
        <div className="cc-variable-bar"><span>Insert</span>{Object.keys(variant.slots).map(key => <button key={key} type="button" onClick={() => insertToken(`[[${key}]]`)}>{key}</button>)}{component.kind === 'body' && value.components.filter(c => c.enabled && (['opener', 'cta', 'custom'].includes(c.kind))).map(c => <button key={c.id} type="button" onClick={() => insertToken(`[[part:${c.id}]]`)}>{c.name} block</button>)}</div>
        {variant.mode === 'ai' && <div className="cc-ai"><Field label="AI instructions" hint="Offer and audience are read from the selected list’s saved research workflow. Generation only happens on your explicit request."><textarea rows={4} value={variant.instructions} onChange={e => updateVariant({ instructions: e.target.value })} placeholder="Use only the selected facts. Keep my tone. One natural sentence; no praise or invented claims." /></Field><p>AI receives the variables configured below, not unrestricted company research. Its output remains a draft for review.</p></div>}
        <details className="cc-settings"><summary><SlidersHorizontal size={14} />Variables and matching <span>{Object.keys(variant.slots).length} variables</span></summary>
          <p>Each variable can draw from several allowed signals. Configure separate variables to combine three, four or more facts in a line.</p>
          {Object.entries(variant.slots).map(([key, slot]) => <section className="cc-slot" key={key}>
            <div className="cc-slot-head"><strong>[[{key}]]</strong><button type="button" onClick={() => { const slots = { ...variant.slots }; delete slots[key]; updateVariant({ slots }); }}>Remove variable</button></div>
            <Field label={`Allowed signals for ${key}`}><select value="" onChange={e => { if (e.target.value) updateVariant({ slots: { ...variant.slots, [key]: { ...slot, signal_ids: [...slot.signal_ids, e.target.value] } } }); }}><option value="">Add a researched signal…</option>{signals.filter(s => s.writing_eligible && !slot.signal_ids.includes(s.id)).map(s => <option key={s.id} value={s.id}>{s.label} · {s.category || 'Uncategorised'}</option>)}</select></Field>
            <ol className="cc-signal-list">{slot.signal_ids.map((id, i) => <li key={id}><span>{signals.find(s => s.id === id)?.label || `Unavailable signal (${id})`}</span><button type="button" aria-label={`Prioritise ${signals.find(s => s.id === id)?.label || id}`} disabled={!i} onClick={() => { const ids = [...slot.signal_ids]; [ids[i - 1], ids[i]] = [ids[i], ids[i - 1]]; updateVariant({ slots: { ...variant.slots, [key]: { ...slot, signal_ids: ids } } }); }}>↑</button><button type="button" aria-label={`Remove ${id} from ${key}`} onClick={() => updateVariant({ slots: { ...variant.slots, [key]: { ...slot, signal_ids: slot.signal_ids.filter(s => s !== id) } } })}>×</button></li>)}</ol>
            <div className="op-grid-two"><Field label="Choose a value"><select value={slot.selection} onChange={e => updateVariant({ slots: { ...variant.slots, [key]: { ...slot, selection: e.target.value as 'priority' | 'strongest' } } })}><option value="priority">My signal order</option><option value="strongest">Strongest available evidence</option></select></Field><Field label="When no signal is available"><select value={slot.required ? 'hold' : 'fallback'} onChange={e => updateVariant({ slots: { ...variant.slots, [key]: { ...slot, required: e.target.value === 'hold', fallback: e.target.value === 'hold' ? '' : slot.fallback } } })}><option value="hold">Hold this variant</option><option value="fallback">Use my fallback text</option></select></Field></div>
            {!slot.required && <Field label="Fallback text (empty is allowed)"><input value={slot.fallback} onChange={e => updateVariant({ slots: { ...variant.slots, [key]: { ...slot, fallback: e.target.value } } })} /></Field>}
          </section>)}
          <div className="op-inline"><Field label="New variable"><input value={slotName} placeholder="location" onChange={e => setSlotName(e.target.value.replace(/[^a-zA-Z0-9_]/g, '').slice(0, 80))} /></Field><button type="button" disabled={!slotName || Object.hasOwn(variant.slots, slotName) || ['__proto__', 'constructor', 'prototype'].includes(slotName)} onClick={() => { updateVariant({ slots: { ...variant.slots, [slotName]: { signal_ids: [], required: true, fallback: '', selection: 'priority' } } }); setSlotName(''); }}>Add variable</button></div>
          <h4>Only use this variant when…</h4>
          {variant.when.map((rule, i) => <div className="cc-rule" key={i}><select aria-label={`Condition ${i + 1} signal`} value={rule.signal_id} onChange={e => updateVariant({ when: variant.when.map((v, n) => n === i ? { ...v, signal_id: e.target.value } : v) })}><option value="">Choose signal</option>{signals.filter(s => s.writing_eligible).map(s => <option value={s.id} key={s.id}>{s.label}</option>)}</select><select aria-label={`Condition ${i + 1} comparison`} value={rule.operator} onChange={e => updateVariant({ when: variant.when.map((v, n) => n === i ? { ...v, operator: e.target.value as typeof rule.operator } : v) })}><option value="present">is available</option><option value="equals">equals</option><option value="contains">contains</option></select>{rule.operator !== 'present' && <input aria-label={`Condition ${i + 1} value`} value={rule.value} onChange={e => updateVariant({ when: variant.when.map((v, n) => n === i ? { ...v, value: e.target.value } : v) })} />}<button type="button" aria-label={`Remove condition ${i + 1}`} onClick={() => updateVariant({ when: variant.when.filter((_, n) => n !== i) })}>×</button></div>)}
          <div className="op-inline"><button type="button" onClick={() => updateVariant({ when: [...variant.when, { signal_id: signals.find(s => s.writing_eligible)?.id || '', operator: 'present', value: '' }] })}>Add condition</button>{variant.when.length > 1 && <select aria-label="Combine conditions" value={variant.match} onChange={e => updateVariant({ match: e.target.value as 'all' | 'any' })}><option value="all">All conditions</option><option value="any">Any condition</option></select>}</div>
          <p>With no conditions, variable coverage decides eligibility. Disabled variants are preserved but never selected.</p>
        </details>
        {component.kind === 'custom' && <details className="cc-settings"><summary>Extra element settings</summary><Field label="Element name"><input value={component.name} onChange={e => updateComponent({ name: e.target.value })} /></Field><Field label="Position"><select value={component.position} onChange={e => updateComponent({ position: e.target.value as CopyComponent['position'] })}><option value="after_opener">After opener</option><option value="after_body">After body</option><option value="after_cta">After CTA</option></select></Field><label className="op-check"><input type="checkbox" checked={component.enabled} onChange={e => updateComponent({ enabled: e.target.checked })} />Include this element</label></details>}
      </div>
    </div>
    <details className="cc-experiment"><summary>A/B test <span>{experiment?.enabled ? experiment.name : 'Off'}</span></summary><p>Test two variants of one element. A company keeps its assignment within a list. Only leads that can use both variants enter the test; others follow normal matching. Save a new experiment identity when changing the hypothesis.</p>
      {!experiment ? <button type="button" onClick={() => onChange({ ...value, experiment: { id: crypto.randomUUID(), name: 'Opener signal test', enabled: false, component_id: component.id, variant_ids: [component.variants[0].id, component.variants[1]?.id || component.variants[0].id], salt: crypto.randomUUID() } })}>Configure a test</button> : <div className="op-grid-two"><Field label="Test name"><input value={experiment.name} onChange={e => onChange({ ...value, experiment: { ...experiment, name: e.target.value } })} /></Field><Field label="Element"><select value={experiment.component_id} onChange={e => { const c = value.components.find(c => c.id === e.target.value)!; onChange({ ...value, experiment: { ...experiment, enabled: false, component_id: c.id, variant_ids: [c.variants[0].id, c.variants[1]?.id || c.variants[0].id] } }); }}>{value.components.filter(c => c.enabled).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>{[0, 1].map(i => <Field key={i} label={`Variant ${i === 0 ? 'A' : 'B'}`}><select value={experiment.variant_ids[i]} onChange={e => { const ids = [...experiment.variant_ids] as [string, string]; ids[i] = e.target.value; onChange({ ...value, experiment: { ...experiment, variant_ids: ids } }); }}>{value.components.find(c => c.id === experiment.component_id)?.variants.filter(v => v.enabled).map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></Field>)}<label className="op-check"><input type="checkbox" checked={experiment.enabled} onChange={e => onChange({ ...value, experiment: { ...experiment, enabled: e.target.checked } })} />Enable balanced assignment</label><button type="button" onClick={() => onChange({ ...value, experiment: { ...experiment, id: crypto.randomUUID(), salt: crypto.randomUUID(), enabled: false } })}>Start a new test identity</button></div>}
    </details>
  </section>;
}
