'use client';
import { useEffect, useMemo, useState } from 'react';
import { renderPipelineTemplate, type Copy, type Draft, type PipelineList, type PipelinePage, type Recipient, type SignalDefinition, type SignalObservation, type TemplatePolicy, type TemplateVersion, type WorkflowVersion } from '@/lib/outbound-pipeline';
import { COPY_PARTS, COPY_LABELS, copyControlFromTemplate, copyControlIssues, renderCopyControl, studioTemplate, type CopyRenderContext, type CopySignal } from '@/lib/copy-control';
import { CopyControlStudio } from './CopyControlStudio';
import { CopyControlResults } from './CopyControlResults';
import { SignalVariations } from './SignalVariations';
import { PipelineJobsPanel } from './PipelineJobsPanel';
import { EvidenceSource } from './EvidenceSource';
import { useDraftHistory } from './useDraftHistory';
import { Field, CommandNotice } from './PipelineForms';
import { PIPELINE_API, queryPath, useEditorBuffer, usePipelineCommand, usePipelineRead, usePipelineCatalogue } from './pipeline-client';
import './copy-control.css';
const emptyTemplate = (): TemplatePolicy => ({ mode: 'deterministic', subject: '', opener: '', body: '', cta: '', unsubscribe: "Reply 'no thanks' and I won't contact you again.", slots: {}, followups: [] });
type Context = { list: PipelineList; workflow: WorkflowVersion; recipient: (Recipient & { current_draft_id?: string }) | null; offer: { id: string; version_no: number; snapshot: Record<string, unknown> } | null; inputs: { signals: Record<string, CopySignal>; values: Record<string, string>; conflicts: string[] }; observations: SignalObservation[]; context: CopyRenderContext; preview_hash: string };
function DocumentValue({ value }: { value: unknown }) {
  if (Array.isArray(value)) return <div>{value.map((item, i) => <DocumentValue key={i} value={item} />)}</div>;
  if (value && typeof value === 'object') return <dl>{Object.entries(value).map(([key, item]) => <div key={key}><dt>{key.replaceAll('_', ' ')}</dt><dd><DocumentValue value={item} /></dd></div>)}</dl>;
  return <p className="op-copy-text">{value == null ? 'Not specified' : String(value)}</p>;
}
export function WriteEditor({ version, lists, list, recipient, signals, writable, onSaved, onDirty, onVersionSaved, onSelectRecipient }: { version: TemplateVersion | null; lists: PipelineList[]; list: PipelineList | null; recipient: Recipient | null; signals: SignalDefinition[]; writable: boolean; onSaved: () => void; onDirty: (dirty: boolean) => void; onVersionSaved: (id: string) => void; onSelectRecipient?: (recipient: Recipient) => void }) {
  const key = `compass.pipeline.write.${list?.id || 'new'}.${version?.id || 'new'}`;
  const [name, setName] = useEditorBuffer(`${key}.name`, version?.name || '');
  const [policy, persistPolicy] = useEditorBuffer<TemplatePolicy>(`${key}.policy`, structuredClone(version?.policy || emptyTemplate()));
  const history = useDraftHistory(policy, persistPolicy), setPolicy = history.change;
  const config = useMemo(() => policy.copy_control || copyControlFromTemplate(policy), [policy]);
  const effective = useMemo(() => studioTemplate(policy, config), [policy, config]);
  const issues = copyControlIssues(config);
  const dirty = name !== (version?.name || '') || JSON.stringify(policy) !== JSON.stringify(version?.policy || emptyTemplate());
  const [revision, bump] = useState(0), [previewOpen, setPreviewOpen] = useState(false), [sampleMode, setSampleMode] = useState(false), [sampleId, setSampleId] = useState('sample-1'), [query, setQuery] = useState(''), [previewVariant, setPreviewVariant] = useState('');
  const [samples, setSamples] = useEditorBuffer<{ id: string; name: string; values: Record<string, string> }[]>('compass.copy-control.samples.v1', [{ id: 'sample-1', name: 'Test lead 1', values: {} }]);
  const [affected, setAffected] = useState<string[]>(list ? [list.id] : []), [overrides, setOverrides] = useState<Record<string, string>>({});
  const [generated, setGenerated] = useState<{ generated: Record<string, string>; preview_hash: string; generation_request_id: string } | null>(null), [generationBusy, setGenerationBusy] = useState(false), [generationError, setGenerationError] = useState('');
  const [generationRequest, setGenerationRequest] = useEditorBuffer<object | null>(`${key}.${recipient?.id || 'none'}.generation-request`, null);
  const command = usePipelineCommand(() => { bump(v => v + 1); onSaved(); }, `${key}.${recipient?.id || 'none'}`);
  const state = usePipelineRead<Context>(list && previewOpen ? `/copy-control?list_id=${encodeURIComponent(list.id)}${recipient ? `&recipient_id=${encodeURIComponent(recipient.id)}` : ''}` : null, revision);
  const context = state.data;
  const candidates = usePipelineCatalogue<Recipient>('recipients', previewOpen && Boolean(list), revision, { list_id: list?.id, q: query || undefined });
  const drafts = usePipelineCatalogue<Draft>('drafts', previewOpen && Boolean(recipient), revision, { recipient_id: recipient?.id });
  const currentDraftId = context?.recipient?.current_draft_id;
  const currentDraftRead = usePipelineRead<PipelinePage<Draft>>(currentDraftId ? queryPath('drafts', { id: currentDraftId }) : null, revision);
  const currentDraft = currentDraftRead.data?.records[0] || null;
  const [manual, setManual] = useEditorBuffer<{ copy: Copy; previousId: string } | null>(`compass.pipeline.recipient.${recipient?.id || 'none'}.draft`, null);
  useEffect(() => { onDirty(dirty || Boolean(manual)); return () => onDirty(false); }, [dirty, manual, onDirty]);
  useEffect(() => { const handler = (e: BeforeUnloadEvent) => { if (dirty || manual) { e.preventDefault(); e.returnValue = ''; } }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty, manual]);
  useEffect(() => { setGenerated(null); setOverrides({}); setGenerationError(''); }, [recipient?.id, version?.id]);
  useEffect(() => { setGenerated(null); }, [policy, overrides, context?.preview_hash]);
  const sample = samples.find(s => s.id === sampleId) || samples[0];
  const inputs = sampleMode ? sample?.values || {} : context?.inputs.values || {};
  const evidence = sampleMode ? Object.fromEntries(signals.map(s => [s.id, { id: s.id, category: s.category || `uncategorised:${s.id}`, value: inputs[s.id] || '', evidence_ids: [], source_ids: [], strength: 0, usefulness: 0, observed_at: '' }])) : context?.inputs.signals || {};
  const renderContext: CopyRenderContext = { ...context?.context, template_version_id: version?.id, evidence, overrides, generated: sampleMode ? undefined : generated?.generated, synthetic: sampleMode || !recipient };
  const previewConfig = useMemo(() => {
    if (!previewVariant) return config;
    const [componentId, variantId] = previewVariant.split('/');
    return { ...config, experiment: null, components: config.components.map(c => c.id === componentId ? { ...c, enabled: true, pinned_variant_id: variantId, variants: c.variants.map(v => v.id === variantId ? { ...v, enabled: true } : v) } : c) };
  }, [config, previewVariant]);
  if (previewVariant) renderContext.synthetic = true;
  const plan = renderCopyControl(previewConfig, inputs, [], renderContext);
  const preview = renderPipelineTemplate({ ...effective, copy_control: previewConfig }, inputs, renderContext);
  const blocked = !writable || command.busy || command.uncertain || generationBusy;
  async function post(body: object) {
    const response = await fetch(PIPELINE_API + '/copy-control', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
    const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Could not complete this action.'); return result;
  }
  async function saveTemplate() {
    const result = await command.save([{ kind: 'template', expected_revision: 0, record: { id: crypto.randomUUID(), name, parent_id: version?.id || null, policy: effective } }]);
    if (result) onVersionSaved(result.results[0].id);
  }
  async function generate(checkPrevious = false) {
    if (!list || !recipient || !version || !context) return;
    if (!checkPrevious && !window.confirm('Generate the selected AI components for this one recipient? This uses the configured AI provider and may incur a charge. It does not send an email.')) return;
    const request = checkPrevious ? generationRequest : { action: 'generate', request_id: crypto.randomUUID(), list_id: list.id, recipient_id: recipient.id, template_version_id: version.id, input_hash: context.preview_hash, confirm_spend: true, overrides };
    if (!request) return;
    setGenerationRequest(request); setGenerationBusy(true); setGenerationError('');
    try { const result = await post(request); setGenerated(result); setGenerationRequest(null); }
    catch (e) { setGenerationError((e as Error).message + ' The same request can be checked without starting a second provider call.'); }
    finally { setGenerationBusy(false); }
  }
  async function savePreview() {
    if (!list || !recipient || !version || !context) return;
    setGenerationError('');
    try {
      const check = await post({ action: 'preview', list_id: list.id, recipient_id: recipient.id, template_version_id: version.id, overrides });
      if (check.context_hash !== context.preview_hash) { bump(v => v + 1); throw new Error('Evidence changed. Review the refreshed preview before saving.'); }
      await command.command('/copy-control', { action: 'save', request_id: crypto.randomUUID(), list_id: list.id, recipient_id: recipient.id, template_version_id: version.id, preview_hash: generated?.preview_hash || check.preview_hash, previous_id: currentDraftId || null, overrides, ...(generated ? { generated: generated.generated, generation_request_id: generated.generation_request_id } : {}) });
    } catch (e) { setGenerationError((e as Error).message); }
  }
  async function saveRevision(copy: Copy, provenance: 'manual' | 'restore', refs: string[], templateId: string, previousId: string | null) {
    if (!recipient) return;
    const adjusted = provenance === 'manual' && copy.copy_control ? { ...copy, copy_control: { ...copy.copy_control, human_edited: true } } : copy;
    const result = await command.save([{ kind: 'draft', expected_revision: 0, record: { id: crypto.randomUUID(), list_id: recipient.list_id, recipient_id: recipient.id, template_version_id: templateId, copy: adjusted, provenance, input_refs: refs, previous_id: previousId } }]);
    if (result) setManual(null);
  }
  return <div className="cc-workspace">
    <header className="cc-header"><div><h2>Copy Control</h2><p>Write the words. Choose the facts. Review the match.</p></div><div className="op-inline"><button type="button" onClick={() => setPreviewOpen(v => !v)} aria-expanded={previewOpen}>{previewOpen ? 'Close preview' : 'Preview & review'}</button><button className="compass-btn-primary" type="submit" form="op-writing-config" disabled={blocked || !name.trim() || issues.length > 0 || !effective.unsubscribe.trim()}>Save template version</button></div></header>
    <div className="cc-version"><input aria-label="Template name" value={name} placeholder="Name this writing template" onChange={e => setName(e.target.value)} disabled={blocked} /><span>{dirty ? 'Unsaved · recovery in this tab' : version ? 'Saved version · edits create a new version' : 'New template'}</span><button type="button" disabled={!history.canUndo || blocked} onClick={history.undo}>Undo</button><button type="button" disabled={!history.canRedo || blocked} onClick={history.redo}>Redo</button><button type="button" disabled={!dirty || blocked} onClick={() => { if (window.confirm('Revert to the saved template? Recipient drafts remain unchanged.')) { setPolicy(structuredClone(version?.policy || emptyTemplate())); setName(version?.name || ''); } }}>Revert</button></div>
    <CommandNotice state={command} />
    {issues.length > 0 && <div className="op-notice" role="status">Before saving: {issues.join(' ')}</div>}
    <form id="op-writing-config" onSubmit={e => { e.preventDefault(); void saveTemplate(); }}><fieldset disabled={blocked}>
      <CopyControlStudio value={config} signals={signals} onChange={next => setPolicy(old => studioTemplate(old, next))} onPreviewVariant={(componentId, variantId) => { setPreviewVariant(`${componentId}/${variantId}`); setPreviewOpen(true); }} />
      <details className="cc-followups"><summary>Follow-ups <span>{policy.followups.length}</span></summary><p>Follow-ups use the existing shared variables and wait at least two days. They are not included in initial-email A/B results.</p>{policy.followups.map((step, i) => <section className="cc-slot" key={i}><div className="op-section-heading"><h4>Follow-up {i + 1}</h4><button type="button" onClick={() => setPolicy(old => ({ ...old, followups: old.followups.filter((_, n) => n !== i) }))}>Remove</button></div><Field label="Days after previous message"><input type="number" min={2} value={step.delay_days} onChange={e => setPolicy(old => ({ ...old, followups: old.followups.map((s, n) => n === i ? { ...s, delay_days: Number(e.target.value) } : s) }))} /></Field>{(['subject', 'body'] as const).map(part => <Field key={part} label={COPY_LABELS[part]}><textarea value={step[part]} onChange={e => setPolicy(old => ({ ...old, followups: old.followups.map((s, n) => n === i ? { ...s, [part]: e.target.value } : s) }))} /></Field>)}</section>)}<button type="button" disabled={policy.followups.length >= 10} onClick={() => setPolicy(old => ({ ...old, followups: [...old.followups, { delay_days: 2, subject: '', body: '' }] }))}>Add follow-up</button><details><summary>Shared follow-up variables</summary><p>Reuse a configured component variable in your follow-ups. This copies its signal priority and fallback into this template’s shared slots; later component edits do not silently change follow-ups.</p><select aria-label="Copy component variable to follow-ups" value="" onChange={e => { const [componentId, variantId, key] = e.target.value.split('/'); const slot = config.components.find(c => c.id === componentId)?.variants.find(v => v.id === variantId)?.slots[key]; if (slot && (!policy.slots[key] || window.confirm(`Replace shared follow-up variable ${key}?`))) setPolicy(old => ({ ...old, slots: { ...old.slots, [key]: { signal_ids: [...slot.signal_ids], required: slot.required, fallback: slot.fallback } } })); }}><option value="">Copy a component variable…</option>{config.components.flatMap(c => c.variants.flatMap(v => Object.keys(v.slots).map(key => <option key={`${c.id}/${v.id}/${key}`} value={`${c.id}/${v.id}/${key}`}>{c.name} · {v.name} · {key}</option>)))}</select>{Object.entries(policy.slots).map(([key, slot]) => <section key={key}><p><strong>[[{key}]]</strong> → {slot.signal_ids.map(id => signals.find(s => s.id === id)?.label || id).join(' / ')}</p><Field label={`Fallback for ${key}`}><input value={slot.fallback} onChange={e => setPolicy(old => ({ ...old, slots: { ...old.slots, [key]: { ...slot, fallback: e.target.value } } }))} /></Field><button type="button" onClick={() => setPolicy(old => ({ ...old, slots: Object.fromEntries(Object.entries(old.slots).filter(([name]) => name !== key)) }))}>Remove shared variable</button></section>)}</details></details>
    </fieldset></form>
    {previewOpen && <section className="cc-preview" aria-label="Copy preview and review">
      <div className="op-section-heading"><h3>Review the match</h3><div className="op-segmented"><button type="button" aria-pressed={!sampleMode} onClick={() => setSampleMode(false)}>Real leads</button><button type="button" aria-pressed={sampleMode} onClick={() => setSampleMode(true)}>Test leads</button></div></div>
      {previewVariant && <p className="op-notice">Testing the selected variant only. Automatic matching may choose a different variant. This test cannot be saved as recipient copy. <button type="button" onClick={() => setPreviewVariant('')}>Return to automatic matching</button></p>}
      {!list && <p className="op-notice">Choose a working list to load its research, offer and real recipients. Test leads never leave this browser.</p>}
      {sampleMode ? <div className="cc-samples"><p className="op-notice">Synthetic test data. Not a real lead, not evidence, and never saved as a recipient draft or counted in results.</p><div className="op-inline"><select aria-label="Test lead" value={sample?.id || ''} onChange={e => setSampleId(e.target.value)}>{samples.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><button type="button" onClick={() => { const id = crypto.randomUUID(); setSamples(old => [...old, { id, name: `Test lead ${old.length + 1}`, values: {} }]); setSampleId(id); }}>New test lead</button>{sample && <input aria-label="Test lead name" value={sample.name} onChange={e => setSamples(old => old.map(s => s.id === sample.id ? { ...s, name: e.target.value } : s))} />}</div><details><summary>Set test signal values</summary>{signals.filter(s => s.writing_eligible).map(s => <Field key={s.id} label={s.label}><input value={sample?.values[s.id] || ''} onChange={e => setSamples(old => old.map(item => item.id === sample?.id ? { ...item, values: { ...item.values, [s.id]: e.target.value } } : item))} /></Field>)}</details></div> : <><div className="op-inline"><input aria-label="Search preview leads" value={query} onChange={e => setQuery(e.target.value)} placeholder="Find a recipient…" /><select aria-label="Preview recipient" value={recipient?.id || ''} onChange={e => { const r = candidates.data?.records.find(r => r.id === e.target.value); if (r) onSelectRecipient?.(r); }}><option value="">Choose a researched recipient</option>{recipient && !candidates.data?.records.some(r => r.id === recipient.id) && <option value={recipient.id}>{recipient.mailbox}</option>}{candidates.data?.records.map(r => <option key={r.id} value={r.id}>{r.mailbox}</option>)}</select>{candidates.data?.next_after && <button type="button" disabled={candidates.loading} onClick={candidates.loadMore}>More recipients</button>}<button type="button" onClick={() => bump(v => v + 1)}>Refresh evidence</button></div>{candidates.error && <p role="alert">{candidates.error}</p>}{state.loading && <p role="status">Loading the complete evidence snapshot…</p>}{state.error && <p role="alert">{state.error}</p>}</>}
      {context?.inputs.conflicts.length && !sampleMode ? <p className="op-notice">Conflicting signals excluded: {context.inputs.conflicts.map(id => signals.find(s => s.id === id)?.label || id).join(', ')}</p> : null}
      {preview.missing.length > 0 && <p className="op-notice" role="status">Held: {preview.missing.join(' · ')}</p>}
      <article className="cc-email" aria-label="Rendered email"><header>{preview.copy.subject || 'Subject not ready'}</header>{(['opener', 'body', 'cta', 'unsubscribe'] as const).map(part => preview.copy[part] && <p className="op-copy-text" key={part}>{preview.copy[part]}</p>)}</article>
      <details className="cc-match"><summary>Why this copy? <span>{plan.trace.signal_combination.join(' + ') || 'No signals selected'}</span></summary>{plan.trace.components.map(c => <section key={c.component_id}><h4>{COPY_LABELS[c.kind]} · {c.variant_name} · {c.mode}</h4>{c.signals.map(s => { const slot = config.components.find(v => v.id === c.component_id)?.variants.find(v => v.id === c.variant_id)?.slots[s.slot]; const overrideKey = `${c.component_id}/${c.variant_id}/${s.slot}`; return <div className="cc-matched" key={s.slot}><strong>[[{s.slot}]] → {s.value}</strong><small>{s.category} · evidence strength {s.strength}/3 · {s.selection}</small>{slot && <select aria-label={`Override ${c.variant_name} ${s.slot}`} value={overrides[overrideKey] || ''} onChange={e => setOverrides(old => e.target.value ? { ...old, [overrideKey]: e.target.value } : Object.fromEntries(Object.entries(old).filter(([key]) => key !== overrideKey)))}><option value="">Use configured selection</option>{slot.signal_ids.filter(id => inputs[id]).map(id => <option key={id} value={id}>{signals.find(v => v.id === id)?.label || id}: {inputs[id]}</option>)}</select>}{!sampleMode && s.source_ids.map(id => <EvidenceSource key={id} id={id} />)}</div>; })}{c.fallback_slots.length > 0 && <p>Fallback text used for: {c.fallback_slots.join(', ')}</p>}</section>)}{plan.trace.experiment && <p>A/B: {plan.trace.experiment.eligible ? `assigned ${plan.trace.experiment.arm}` : plan.trace.experiment.reason}</p>}</details>
      {!sampleMode && <><div className="op-inline">{plan.pending_ai.length > 0 && <button type="button" disabled={blocked || dirty || Boolean(previewVariant) || !version?.policy.copy_control || !context || !recipient || Boolean(generationRequest)} onClick={() => void generate()}>Generate AI components</button>}{generationRequest && <><button type="button" disabled={generationBusy} onClick={() => void generate(true)}>Check previous generation</button><button type="button" disabled={generationBusy} onClick={() => { if (window.confirm('Keep the previous request recorded but allow a new attempt? The previous provider call may have incurred a charge.')) setGenerationRequest(null); }}>Allow a new attempt</button></>}<button type="button" disabled={blocked || dirty || Boolean(previewVariant) || !version?.policy.copy_control || !context || Boolean(state.error) || state.loading || !recipient || preview.missing.length > 0 || Boolean(manual)} onClick={() => void savePreview()}>Save recipient draft</button></div>{(dirty || !version?.policy.copy_control) && <p className="op-muted">Save a Copy Control template version before generating or saving recipient copy. Your live preview can still be edited.</p>}{generated && <p className="op-notice">AI draft generated. Check every claim and the full email before saving. Nothing has been sent.</p>}{generationError && <p role="alert">{generationError}</p>}</>}
      <details className="cc-offer"><summary>Offer & audience used by this list</summary>{context?.offer ? <><p>Offer snapshot v{context.offer.version_no} · {context.offer.id}</p><DocumentValue value={context.offer.snapshot} /><h4>Audience criteria · {context.workflow.policy.icp_name || context.workflow.name}</h4>{context.workflow.policy.criteria.map(c => <p key={c.id}>{c.label}: {c.instructions}</p>)}</> : <p>No saved offer document is available for this list. AI generation is held until one is linked.</p>}</details>
      {recipient && !sampleMode && <details className="cc-drafts"><summary>Saved recipient draft & history</summary>{currentDraftRead.error && <p role="alert">{currentDraftRead.error}</p>}{drafts.error && <p role="alert">{drafts.error}</p>}{currentDraft ? <><p>{currentDraft.provenance} · {currentDraft.approved ? 'Approved snapshot' : 'Unapproved draft'} · edits create a new revision.</p>{COPY_PARTS.map(part => <Field key={part} label={COPY_LABELS[part]}><textarea value={(manual?.copy || currentDraft.copy)[part]} disabled={blocked} onChange={e => setManual({ copy: { ...(manual?.copy || currentDraft.copy), [part]: e.target.value }, previousId: manual?.previousId || currentDraft.id })} /></Field>)}<button type="button" disabled={blocked || !manual} onClick={() => manual && void saveRevision(manual.copy, 'manual', currentDraft.input_refs, currentDraft.template_version_id, manual.previousId)}>Save recipient revision</button>{manual && <button type="button" onClick={() => { if (window.confirm('Discard only this unsaved recipient edit?')) setManual(null); }}>Discard recipient edit</button>}</> : <p>No recipient draft yet. Review the copy above and save it.</p>}{drafts.data?.records.filter(d => d.id !== currentDraft?.id).map(d => <article className="cc-old-draft" key={d.id}><strong>{d.provenance} · {new Date(d.created_at).toLocaleString('en-AU')}</strong><p className="op-copy-text">{COPY_PARTS.map(part => d.copy[part]).filter(Boolean).join('\n\n')}</p><button type="button" disabled={blocked || Boolean(manual)} onClick={() => void saveRevision(d.copy, 'restore', d.input_refs, d.template_version_id, currentDraft?.id || null)}>Restore as new revision</button></article>)}{drafts.data?.next_after && <button type="button" disabled={drafts.loading} onClick={drafts.loadMore}>Older drafts</button>}</details>}
    </section>}
    <details className="cc-apply"><summary>Apply saved template to lists</summary><p>Freeze the affected recipients before applying. Manual edits are protected by default. Initial drafts can be saved from Preview or created by the connected Write executor; this bulk tool revises existing drafts.</p>{lists.map(item => <label className="op-check" key={item.id}><input type="checkbox" checked={affected.includes(item.id)} onChange={e => setAffected(old => e.target.checked ? [...old, item.id] : old.filter(id => id !== item.id))} />{item.name}</label>)}<PipelineJobsPanel key={`apply.${list?.id}.${version?.id}`} kind="template_apply" listId={list?.id || ''} listIds={affected} templateId={version?.id} writable={writable} dirty={dirty} onSaved={() => { bump(v => v + 1); onSaved(); }} /></details>
    <CopyControlResults writable={writable} />
    {version && !version.policy.copy_control && <details className="cc-legacy"><summary>Original legacy template · read only</summary><p>Saving the editor above creates a new component-based version. This original remains unchanged.</p><fieldset disabled><SignalVariations policy={version.policy} signals={signals} onChange={() => {}} /></fieldset></details>}
  </div>;
}
