const params=new URLSearchParams(location.search), direction=params.get('direction')||'meridian', screen=params.get('screen')||'home', state=params.get('state')||'ready';
document.body.classList.add(direction);document.body.dataset.screen=screen;document.title=`Compass · ${direction} · ${screen}`;
const names={meridian:'Meridian',edition:'Edition',signal:'Signal'};
const url=(s)=>`concept.html?direction=${direction}&screen=${s}`;
const btn=(label,action='',primary=false)=>`<button class="btn ${primary?'primary':''}" data-action="${action}">${label}</button>`;
const link=(label,s,primary=false)=>`<a class="btn ${primary?'primary':''}" href="${url(s)}">${label}</a>`;
const badge=(text,kind='')=>`<span class="badge ${kind}">${text}</span>`;
const eyebrow=t=>`<div class="eyebrow">${t}</div>`;
const brand=`<div class="brand"><span class="brand-mark" aria-hidden="true">↗</span><span class="brand-word">compass<span style="color:var(--accent)">.</span></span></div>`;
const groups=[['Today',[['01','Home','home'],['02','Inbox','inbox'],['03','Tasks','tasks'],['04','Calendar','calendar']]],['Growth',[['05','Outbound','outbound'],['06','CRM','crm']]],['Delivery',[['07','Clients','clients'],['08','Installs','installs']]],['Workspace',[['09','Planning','planning'],['10','Settings','settings']]]];
const navItems=groups.map(([title,items])=>`<div class="nav-group">${eyebrow(title)}${items.map(([n,title,s])=>`<a class="nav-item ${s===screen||(screen==='editor'&&s==='outbound')?'active':''}" href="${['home','inbox','outbound','editor'].includes(s)?url(s):'#'}" ${!['home','inbox','outbound','editor'].includes(s)?`data-action="scope:${s}"`:''}><span>${n}</span>${title}</a>`).join('')}</div>`).join('');
const sidebar=`<aside class="sidebar">${brand}${navItems}<div class="sidebar-foot">Switchflow<br><small>Jules · Operator workspace</small></div></aside>`;
const topbar=direction==='edition'?`<header class="topbar">${brand}<nav class="top-links" aria-label="Primary">${['home','inbox','outbound'].map(s=>`<a class="${screen===s?'active':''}" href="${url(s)}">${s==='home'?'Today':s==='outbound'?'Growth':'Inbox'}</a>`).join('')}<a href="#" data-action="scope:clients">Delivery</a><a href="#" data-action="scope:planning">Planning</a></nav><div class="actions">${eyebrow('Switchflow / Jules')}<button class="mobile-menu" data-action="menu" aria-label="Open navigation">☰</button></div></header><nav class="subnav" aria-label="Workspace">${['Tasks','Calendar','CRM','Clients','Installs','Settings'].map(t=>`<a href="#" data-action="scope:${t.toLowerCase()}">${t}</a>`).join('')}</nav>`:`<header class="topbar"><div class="breadcrumb"><strong>Switchflow</strong><span>/</span><span>${screen==='editor'?'Outbound / Sydney Hvac':screen.charAt(0).toUpperCase()+screen.slice(1)}</span></div><div class="mobile-menu">${brand}</div><div class="actions"><span class="desktop-only muted">${direction==='signal'?'OPERATOR WORKSPACE':'Tuesday, 8 September'}</span><button class="mobile-menu" data-action="menu" aria-label="Open navigation">☰</button><span class="avatar desktop-only">JH</span></div></header>`;
function heading(kicker,title,sub,actions=''){return `<div class="page-heading"><div>${eyebrow(kicker)}<h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div><div class="actions">${actions}</div></div>`}
const stats=`<section class="panel"><div class="panel-head row"><h3>Outbound pulse</h3>${badge('Snapshot')}</div><div class="facts"><div class="fact">${eyebrow('Sent today')}<strong>162</strong><small>Instantly</small></div><div class="fact">${eyebrow('Reply rate')}<strong>1.3<span style="font-size:19px">%</span></strong><small>Reported by Instantly</small></div></div><div class="source-note">8 SEP · 18:27 AEST<br>Snapshot figures; sending status needs review.</div></section>`;
const waiting=`<section class="panel"><div class="panel-head row"><h3>Waiting on others</h3>${badge('Blocked')}</div><div class="waiting">${eyebrow('Roof Safety')}<h3>Internal decision pending</h3><p>They will speak with their boss about websites and advertising. No follow-up date agreed.</p><a class="btn text" href="${url('inbox')}">Read context <span>↗</span></a></div></section>`;
function home(){return heading('Tuesday / 08 September 2026',direction==='edition'?'The day’s work.':direction==='signal'?'Today / Prepare':'A clear path for today.','Review the brief, move one campaign forward, keep waiting work in view.',btn('Capture a thought','capture'))+`<div class="home-grid"><div><section class="panel focus"><div class="panel-content"><div class="row">${eyebrow(direction==='edition'?'The lead story':direction==='signal'?'01 / Next decision':'Next decision')}${badge('Brief awaiting review','warn')}</div><h2>Review installation candidates.<br>Finish one precise draft.</h2><p>Start with existing Sydney companies. Check relevance and prior contact before building the next campaign.</p><div class="actions">${btn('Review today’s brief &nbsp; ↗','brief',true)}${link('Open Sydney Hvac','editor')}</div></div><div class="focus-footer"><span>From today’s operator brief</span>${badge('Preparation only')}</div></section><section class="panel work-list"><div class="panel-head row"><h3>${direction==='signal'?'Work queue':'Continue the work'}</h3><span class="small">From the current brief</span></div><div class="work-row"><span class="number">01</span><div><h3>Sydney installation candidates</h3><p>Research fit, then reconcile previous contact.</p></div>${btn('Review inventory ↗','scope:crm')}</div><div class="work-row"><span class="number">02</span><div><h3>Sydney Hvac</h3><p>Draft sequence · copy and opener review outstanding.</p></div>${link('Continue draft ↗','editor')}</div><div class="work-row"><span class="number">03</span><div><h3>Payment connection</h3><p>Signing awaits verified receiving instructions.</p></div>${btn('View setup ↗','scope:settings')}</div></section><div class="capture"><div><h3>Make room for a thought.</h3><p>Capture first. Turn it into work when you’re ready.</p></div>${btn('＋ Capture','capture')}</div></div><aside class="stack">${stats}${waiting}<section class="panel"><div class="panel-content">${eyebrow('Inbox / retained queue')}<div class="queue-count"><span>Agent items</span><b>4</b></div><div class="queue-count"><span>Instantly items</span><b>50</b></div><div class="queue-count"><span>Lead items</span><b>33</b></div><a class="btn text" href="${url('inbox')}">Review queue ↗</a></div></section></aside></div>`}
const taskTitles=['Await Roof Safety’s internal decision','Client outcome reporting','Enquiry-to-booking delivery workflow','Onboarding and baseline capture'];
const listRows=taskTitles.map((t,i)=>`<button class="inbox-item ${i===0?'selected':''}" data-action="${i===0?'detail':'item:'+i}"><div class="row">${badge(i===0?'Waiting':'Agent task',i===0?'warn':'')}<small>8 Sep</small></div><h3>${t}</h3><p>${i===0?'Websites and advertising · internal decision':'Open the task to review the work and its context.'}</p></button>`).join('');
function inbox(){return heading('Communications / Triage','Inbox','Keep the conversation, the decision, and the next action together.',btn('Queue guide','queue-guide'))+`<nav class="tabbar" aria-label="Inbox sources"><button class="active" data-action="agents">Agents <span class="muted">4</span></button><button data-action="channel:Instantly">Instantly <span class="muted">50</span></button><button data-action="channel:Leads">Leads <span class="muted">33</span></button><span class="eyebrow" style="margin-left:auto;white-space:nowrap">Queue items · 8 Sep snapshot</span></nav><div class="panel inbox-layout"><section class="inbox-list"><div class="filter-row"><button data-action="all" class="active">All agent items</button><button data-action="waiting">Waiting</button></div>${listRows}</section><article class="message"><button class="mobile-back" data-action="back">← Back to queue</button><div class="row">${eyebrow('Agent task / Roof Safety')}${badge('Blocked','warn')}</div><h2>Await Roof Safety’s<br>internal decision</h2><p class="small">Updated 8 September · Source: daily setup</p><div class="body-copy">The conversation happened. Roof Safety asked for website and advertising ideas for two companies and will speak with his boss before making decisions.</div><div class="decision">${eyebrow('What happens next')}<h3>Wait for their internal decision.</h3><p>No unanswered call request. No agreed follow-up date. This is a pending opportunity.</p></div><div class="actions">${btn('Open linked task ↗','scope:tasks',true)}${btn('Snooze','prototype-snooze')}${btn('More ···','triage')}</div><div class="metadata"><div>${eyebrow('Task type')}<p>Sell</p></div><div>${eyebrow('Commercial outcome')}<p>Uncertain</p></div><div>${eyebrow('Source')}<p>Daily setup</p></div><div>${eyebrow('Related workflow')}<p>Websites & advertising</p></div></div></article></div>`}
const initial=`The service I’m offering handles follow-up on existing ducted-installation enquiries: collecting the job details, arranging suitable quote appointments and sending reminders.\n\nIt works around your existing estimating process.`;
const followup=`When a homeowner enquires about ducted aircon, is following up and getting a suitable quote appointment booked a headache, or is that already covered?\n\nIf useful, I can send a one-page outline of the follow-up process.`;
const inspector=`<section class="panel"><div class="panel-content">${eyebrow('Campaign context')}<h3>Installation booking</h3><p class="small">HVAC · Sydney</p><div class="check"><b>○</b> Copy not confirmed</div><div class="check"><b>○</b> Opener review outstanding</div><div class="check"><b>○</b> Instantly not linked</div>${btn('Review preparation','preparation')}</div></section><section class="panel" style="margin-top:18px"><div class="panel-content">${eyebrow('Writing tools')}<h3>Make every line earn its place.</h3><p class="small">Source and yours remain labelled. Open the library when you need it.</p>${btn('Open component library','library')}${btn('QA & variables','qa')}</div></section>`;
const signalInspector=`<section class="panel"><div class="panel-head">${eyebrow('Rendered / unresolved variables')}</div><div class="panel-content"><h3>ducted installation enquiries</h3><div class="preview-copy">{{personalization}}<br><br>${initial.replaceAll('\n','<br>')}<br><br>Would a one-page outline of that process be useful, or is follow-up already covered?<br><br>Jules<br>Switchflow</div><div class="check"><b>○</b> Select a verified lead before checking final merge output.</div></div></section>`;
function editor(){return heading('Outbound / Sequence','Sydney Hvac','Installation booking · Draft · Snapshot of saved Compass copy',btn('Save draft','save')+btn('Review preparation ↗','preparation',true))+`<nav class="tabbar" aria-label="Campaign workspace"><button class="active" data-action="compose">Sequence</button><button data-action="leads">Leads</button><button data-action="analytics">Results</button><button data-action="experiment">Experiment</button><button data-action="archive">Archive</button><button data-action="preparation">Settings</button></nav><div class="editor-tools">${btn('Library','library')}${btn('QA & variables','qa')}${btn('Preparation','preparation')}</div><div class="editor-layout"><nav class="steps" aria-label="Sequence steps">${eyebrow('Sequence')}<button class="step active" data-action="step:1"><small>DAY 0</small><strong>01 &nbsp; Initial enquiry</strong><small>Published opener + service</small></button><div class="step-delay">↓ &nbsp; Wait 3 days</div><button class="step" data-action="step:2"><small>DAY 3</small><strong>02 &nbsp; Follow-up</strong><small>Diagnostic question</small></button>${btn('＋ Follow-up','add-step')}</nav><article class="paper"><div class="paper-toolbar">${eyebrow('01 / Initial enquiry')}${btn('Preview ↗','preview')}</div><div class="subject"><label class="eyebrow" for="subject">Subject</label><input id="subject" value="ducted installation enquiries"></div><div class="letter"><div id="first-letter"><div class="slot-label">Published factual opener</div><span class="token">{{personalization}}</span><div class="slot-label">Service</div><textarea aria-label="Service copy">${initial}</textarea><div class="slot-label">Permission CTA</div><p>Would a one-page outline of that process be useful, or is follow-up already covered?</p></div><div id="second-letter" hidden><div class="slot-label">Diagnostic follow-up</div><textarea aria-label="Follow-up copy">${followup}</textarea></div><p>Jules<br>Switchflow</p><p class="optout">Not relevant? Reply unsubscribe and I’ll leave it there.</p><details><summary class="small">Optional copy blocks</summary><p class="small">Who · Why · Risk reversal · Availability · P.S.</p>${btn('Choose a block','library')}</details></div><div class="editor-foot row"><span id="save-state">Saved source · 8 Sep, 19:32 AEST</span>${btn('Save draft','save')}</div></article><aside class="inspector">${direction==='signal'?signalInspector:inspector}</aside></div>`}
function outbound(){return heading('Growth / Campaigns','Outbound','Prepare deliberately. Review the evidence. Launch in Instantly.',btn('New campaign','new-campaign',true))+`<nav class="tabbar" aria-label="Outbound views"><button class="active" data-action="waves">Campaigns</button><button data-action="scope:calendar">Calendar</button><button data-action="timeline">Timeline</button><button data-action="library">Craft library</button><button data-action="scope:offers">Offers & tests</button></nav><div class="outbound-note">${eyebrow('Today’s direction')}<h3>Review existing installation candidates and finish one precise draft.</h3><p>Smart Handy is followed up. Roof Safety awaits an internal decision.</p></div><div class="outbound-grid"><section class="panel"><div class="panel-head row"><h3>Next campaigns</h3>${badge('Compass preparation lane')}</div><table class="queue-table"><thead><tr><th>CAMPAIGN</th><th>MARKET</th><th>CONTEXT</th><th></th></tr></thead><tbody><tr><td>Sydney Hvac<span class="sub">Installation booking · Draft</span></td><td>Sydney</td><td>Review copy</td><td>${link('Open ↗','editor')}</td></tr><tr><td>Melbourne Plumber<span class="sub">Plumber · Melbourne</span></td><td>Melbourne</td><td>Linked to Instantly</td><td>${btn('Inspect','campaign:Melbourne Plumber')}</td></tr><tr><td>HVAC | AU | 50 | capture 24 aug<span class="sub">HVAC · AU</span></td><td>AU</td><td>Linked to Instantly</td><td>${btn('Inspect','campaign:HVAC AU')}</td></tr></tbody></table></section><aside class="stack"><section class="panel"><div class="panel-content">${eyebrow('Recommended')}<h3 style="margin:12px 0">Sydney Locksmith | 65 | Sep</h3><p class="small">Agent recommendation. Review current campaign context before moving it.</p>${btn('Review recommendation','campaign:Sydney Locksmith')}</div></section><section class="panel"><div class="panel-content">${eyebrow('Sending status')}<h3 style="margin:12px 0">Check the source.</h3><p class="small">The Waves board showed no live campaigns; the older Home snapshot retained sending figures. Resolve freshness before acting.</p>${btn('Source details','source')}</div></section></aside></div>`}
function states(){if(state==='loading')return `<section class="panel state-card" aria-busy="true">${eyebrow('Loading '+screen)}<h2>Bringing your workspace into view.</h2><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div><p>Fetching this view’s records.</p></section>`;if(state==='error')return `<section class="panel state-card" role="alert">${eyebrow('Connection interrupted')}<h2>We couldn’t refresh ${screen}.</h2><p>Your work stays in place. Retry this view when the connection is available.</p>${btn('Retry this view','retry',true)}</section>`;return `<section class="panel state-card">${eyebrow('Nothing in this view')}<h2>${screen==='inbox'?'No items match this queue.':'A clear starting point.'}</h2><p>${screen==='inbox'?'Check another source or return to all items.':'Choose an existing campaign or capture the next piece of work.'}</p>${btn(screen==='inbox'?'Show all items':'Return to workspace','retry',true)}</section>`}
const bottom=`<nav class="bottom-nav" aria-label="Mobile primary">${[['⌂','Home','home'],['▱','Inbox','inbox'],['↗','Outbound','outbound']].map(([i,t,s])=>`<a class="${s===screen||(screen==='editor'&&s==='outbound')?'active':''}" href="${url(s)}"><span aria-hidden="true">${i}</span>${t}</a>`).join('')}<button data-action="menu"><span aria-hidden="true">☰</span>More</button></nav>`;
document.querySelector('#app').innerHTML=`<div class="shell">${sidebar}<div class="workspace">${topbar}<main class="main" id="main">${state!=='ready'?states():({home,inbox,editor,outbound}[screen]||home)()}<div class="design-stamp">${names[direction].toUpperCase()} / DESIGN CONCEPT · 8 SEP 2026 DATA SNAPSHOT · PROTOTYPE ACTIONS DO NOT CHANGE COMPASS</div></main></div></div>${bottom}`;
const dialog=document.querySelector('#dialog'), content=document.querySelector('#dialog-content');let returnFocus;
function show(title,body){returnFocus=document.activeElement;content.innerHTML=eyebrow('Compass / Design study')+`<h2>${title}</h2>${body}`;dialog.showModal()}
function toast(text){const t=document.querySelector('.toast');t.textContent=text;t.hidden=false;setTimeout(()=>t.hidden=true,4200)}
document.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>returnFocus?.focus());
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;e.preventDefault();const a=el.dataset.action;
if(a==='menu'){show('Your workspace',`<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">${groups.flatMap(g=>g[1]).map(([n,t,s])=>['home','inbox','outbound'].includes(s)?link(t,s):btn(t,'scope:'+s)).join('')}</div>`);return}
if(a.startsWith('scope:')){const s=a.split(':')[1];const desc={tasks:'One task list with Do next, In progress and Waiting views. Keep status, priority, due date, project, notes and completion evidence.',calendar:'Promote the existing campaign calendar to a direct navigation destination. Keep go-live dates, scheduling and timeline views. Do not invent appointments or time blocks.',crm:'Preserve the Compass lead ledger, filters, bulk actions and fact provenance. Use a readable table with a record inspector; compact contact cards on phones.',clients:'Client directory with a focused detail workspace: communication, work, onboarding, agreements, invoices and channels.',installs:'An installation work queue with stage, dependency and evidence detail. Empty and unavailable are different states.',planning:'Connect goals and notes to existing projects and tasks, with a calm writing surface and a linked work index.',settings:'Group existing integrations by purpose. Show the actual connection state and last sync; keep account actions explicit.',offers:'Offers, economics and experiments remain reachable within Growth; preserve the existing contracts and test-cell semantics.'};show(s.charAt(0).toUpperCase()+s.slice(1),`<p>${desc[s]||'Existing capability retained within the new navigation.'}</p><p class="small">This surface is planned for implementation after the reference screen is approved.</p>`);return}
if(a==='brief'){show('Today’s operator brief',`<p>Review existing installation candidates and finish one precise draft. Smart Handy is followed up; Roof Safety awaits an internal decision. Signing awaits payment connection.</p><div class="decision">${eyebrow('Next decision')}<p>Review existing companies against the Sydney residential ducted installation brief. Research fit is not sales qualification. Reconcile prior contact before assigning a cohort.</p></div><p>Preparation only. The new Sydney campaign remains a draft.</p><div class="actions">${btn('Accept brief','accept',true)}${btn('Dismiss','dismiss')}</div><p class="small">Snapshot of the 8 September brief. These buttons demonstrate feedback without writing to Compass.</p>`);return}
if(['accept','dismiss','prototype-snooze'].includes(a)){if(dialog.open)dialog.close();toast(`Prototype: ${a==='accept'?'brief accepted':a==='dismiss'?'brief dismissed':'item snoozed'}. Live Compass is unchanged.`);return}
if(a==='capture'){show('Capture a thought.',`<p>Put the loose thought here. Review suggested tasks before adding them.</p><textarea aria-label="Thought" placeholder="What’s on your mind?"></textarea>${btn('Review possible next steps','capture-review',true)}`);return}
if(a==='capture-review'){const t=content.querySelector('textarea').value;if(!t.trim()){content.querySelector('textarea').focus();return}show('Review before adding work.',`<p id="thought"></p><p class="small">Production will call Compass’s existing brain-dump suggestion flow and preserve explicit selection before creating tasks.</p>`);content.querySelector('#thought').textContent=t;return}
if(a==='detail'){document.querySelector('.inbox-layout').classList.add('detail');document.querySelector('.mobile-back').focus();return}
if(a==='back'){document.querySelector('.inbox-layout').classList.remove('detail');document.querySelector('[data-action=detail]').focus();return}
if(a==='waiting'||a==='all'){document.querySelectorAll('.inbox-item').forEach((x,i)=>x.hidden=a==='waiting'&&i>0);document.querySelectorAll('.filter-row button').forEach(x=>x.classList.toggle('active',x===el));return}
if(a.startsWith('step:')){const second=a.endsWith('2');document.querySelector('#first-letter').hidden=second;document.querySelector('#second-letter').hidden=!second;document.querySelector('.paper-toolbar .eyebrow').textContent=second?'02 / Follow-up':'01 / Initial enquiry';document.querySelector('#subject').value=second?'':'ducted installation enquiries';document.querySelectorAll('.step').forEach(x=>x.classList.toggle('active',x===el));return}
if(a==='save'){toast('Prototype: draft saved for this view. No campaign was updated.');document.querySelector('#save-state').textContent='Prototype save acknowledged';return}
if(a==='preview'){const body=document.querySelector('#second-letter').hidden?document.querySelector('[aria-label="Service copy"]').value:document.querySelector('[aria-label="Follow-up copy"]').value;show('Email preview',`<p id="preview-subject" style="font-weight:700;color:var(--ink)"></p><div id="preview-body" style="white-space:pre-wrap;line-height:1.8"></div><p class="small">Merge values remain unresolved until a real lead is selected.</p>`);content.querySelector('#preview-subject').textContent=document.querySelector('#subject').value||'Same thread';content.querySelector('#preview-body').textContent=(document.querySelector('#second-letter').hidden?'{{personalization}}\n\n':'')+body+(document.querySelector('#second-letter').hidden?'\n\nWould a one-page outline of that process be useful, or is follow-up already covered?':'')+'\n\nJules\nSwitchflow\n\nNot relevant? Reply unsubscribe and I’ll leave it there.';return}
if(a==='retry'){location.href=url(screen);return}
const modal={
'preparation':['Prepare for Instantly',`<p>Sydney Hvac is a draft. The saved record has no Instantly link; copy confirmation and opener review are outstanding.</p><div class="check">○ Confirm copy</div><div class="check">○ Review openers</div><div class="check">○ Verify cohort and rendered merges</div><p>Keep launch as an explicit action in Instantly.</p><p class="small">Existing data contracts are retained. No readiness percentage is invented.</p>`],
'library':['A library for writing.',`<p>Separate yours from source material. Browse structures, subjects, openers, expressions, CTAs, templates and offers.</p><div class="decision">${eyebrow('Current structure / source')}<h3>Connor 3-paragraph</h3><p>Current campaign structure retained. Selection is a writing decision, not a style redesign.</p></div><p class="small">Production library opens as a full-width comparison surface, preserving provenance and insertion behaviour.</p>`],
'qa':['Check the actual email.',`<p>Keep variable validation, signature, opt-out and copy warnings next to the draft. Preview with a real selected lead.</p><p>Follow-up delay: 3 days, from the saved sequence.</p><p class="small">No invented recipient or substituted personalisation appears in this concept.</p>`],
'queue-guide':['A queue with clear scope.',`<p>Agents: 4 items. Instantly: 50 retained queue items. Leads: 33 queue items.</p><p>These are the 8 September Inbox source counts. They do not mean 87 new replies. Home’s Instantly waiting count comes from a different snapshot.</p>`],
'source':['Freshness is part of the design.',`<p>The 18:27 AEST Home snapshot reports sent volume and reply rate. The later Waves screen shows no live campaigns. The redesign labels these separately instead of combining them into a fictional all-clear.</p>`],
'analytics':['Results, when there is evidence.',`<p>No Instantly link is present for this draft. Connect the campaign and allow real delivery results to arrive before showing performance.</p>`],
'leads':['Campaign leads',`<p>Retain assigned records, filters and lead preview. The current brief says qualified cohort assignment remains outstanding; this concept does not invent a sendable count.</p>`],
'archive':['Copy history',`<p>Keep saved revisions and source context attached to the campaign, with explicit restore and comparison actions.</p>`],
'experiment':['One change, traceable evidence.',`<p>Current campaign: exploratory, solo, queued. Preserve hypothesis, factor, parent campaign and outcome maturity. Do not present a statistical winner.</p>`],
'new-campaign':['Start with the campaign brief.',`<p>Production retains the existing campaign creation flow: name, offer, market, sequence and saved draft. This study does not create records.</p>`],
'add-step':['Follow-up timing',`<p>Keep the current three-day follow-up. Any additional step is explicitly added by the operator; no sequence is changed in this concept.</p>`],
'triage':['Handle this item',`<div class="actions">${btn('Mark read','prototype-snooze')}${btn('Done','prototype-snooze')}${btn('Create task','scope:tasks')}</div><p class="small">Production retains triage, undo, lifecycle and source-specific actions.</p>`]
};
if(a.startsWith('channel:')){show(a.split(':')[1]+' queue',`<p>This study shows the populated Agents queue. Production uses the existing source payload, preserves source-specific classification and opens replies in Instantly or Gmail.</p>`);return}
if(a.startsWith('item:')){show(taskTitles[Number(a.split(':')[1])],'<p>Verified title from the live Agents queue. The record body was not copied into this study.</p>');return}
if(a.startsWith('campaign:')){show(a.split(':')[1],'<p>Existing campaign retained. The Sydney Hvac editor is the fully drawn campaign example in this study.</p>');return}
if(modal[a])show(...modal[a]);else toast('Design concept: this view is included in the production rollout plan.');
});
document.addEventListener('input',e=>{if(e.target.closest('.paper'))document.querySelector('#save-state').textContent='Unsaved prototype changes'});
